import type { Choice } from "./curriculum";

const q = (prompt: string, options: string[], answer: number, explanationIt: string): Choice => ({
  prompt,
  options,
  answer,
  explanationIt: `Soluzione: ${options[answer]}. ${explanationIt}`,
});

export const advancedNuanceQuestions: Record<string, Choice[]> = {
  "b1-present-perfect": [
    q("Aspetto · Quale frase presenta un'attività iniziata nel passato e ancora in corso?", ["I have been working here since March.", "I worked here until March.", "I had worked here before March.", "I will work here from March."], 0, "Have been working since March collega l'inizio passato alla durata ancora in corso."),
    q("Risultato o durata · Quale frase mette in primo piano il risultato completato?", ["I have written three reports today.", "I have been writing reports all day.", "I was writing a report at noon.", "I wrote reports when I worked there."], 0, "Have written three reports quantifica il risultato; have been writing mette in rilievo l'attività."),
  ],
  "b1-past-vs-perfect": [
    q("Tempo concluso · Il contatto con il cliente è avvenuto ieri. Quale frase lo colloca in quel tempo concluso?", ["I saw the client yesterday.", "I have seen the client recently.", "I had seen the client before the meeting.", "I have been seeing the client regularly."], 0, "I saw the client yesterday. usa il Past Simple perché yesterday è un riferimento temporale concluso."),
    q("Esperienza · Quale domanda non chiede un momento preciso?", ["Have you ever worked abroad?", "When did you work abroad?", "Did you work abroad in 2022?", "How long did that contract last?"], 0, "Have you ever chiede un'esperienza senza data; le altre domande delimitano il passato."),
  ],
  "b1-conditionals": [
    q("Grado di realtà · Quale frase presenta il viaggio come possibile, ma dipendente da una condizione concreta?", ["If the client confirms today, we will travel tomorrow.", "If the client confirmed today, we would travel tomorrow.", "If the client had confirmed, we would have travelled yesterday.", "When the client confirms, we always travel the next day."], 0, "If the client confirms today, we will travel tomorrow. usa il first conditional per una possibilità futura reale."),
  ],
  "b1-passive": [
    q("Scelta del focus · In quale frase il processo conta più di chi lo esegue?", ["Each application is reviewed within two working days.", "Our senior coordinator reviews each application personally.", "Someone reviews applications, but I do not know when.", "The coordinator has chosen to review only one application."], 0, "Each application is reviewed within two working days. mette in primo piano procedura e tempi, non l'agente."),
  ],
  "b1-work-collocations": [
    q("Collocazione e intenzione · Quale frase indica avanzamento verso un risultato?", ["We have made progress on the report.", "We have done progress on the report.", "We have worked progress on the report.", "We have taken progress from the report."], 0, "Make progress è la collocazione che esprime avanzamento verso un risultato."),
  ],
  "b1-review-problem-solving": [
    q("Problema ancora aperto · Non indichi un momento concluso e il ritardo ha una conseguenza adesso. Quale frase lo comunica?", ["The report has been delayed, so we need a new deadline.", "The report was delayed last Tuesday, but the deadline was adjusted that day.", "The report had been delayed before the revised schedule was approved.", "The report is delayed whenever the source data arrive late."], 0, "Has been delayed presenta un risultato attuale e la passiva identifica ciò che ha subito il ritardo."),
    q("Condizione reale · Quale frase presenta una possibilità futura concreta, non un'ipotesi remota o un rimpianto?", ["If the figures arrive today, we will finish tomorrow.", "If the figures arrived today, we would finish tomorrow.", "If the figures had arrived yesterday, we would have finished today.", "When the figures arrive on time, we usually finish the next day."], 0, "First conditional: if + Present Simple, quindi will + forma base."),
    q("Responsabilità · Quale passiva descrive il problema senza attribuire una colpa non dimostrata?", ["The figures were omitted from the report.", "The figures were deliberately omitted by Paolo.", "Paolo appears to have omitted the figures from the report.", "The report confirms that Paolo chose to omit the figures."], 0, "La passiva descrive il fatto senza aggiungere un responsabile o un'intenzione non provati."),
  ],
  "b1-workplace-meetings": [
    q("Aggiornamento · Quale frase comunica un risultato rilevante ora senza indicare quando?", ["We have completed the accessibility test.", "We completed the accessibility test yesterday.", "We were completing the test at noon.", "We had completed it before the meeting started."], 0, "Present Perfect senza data aggiorna sul risultato attuale; le altre forme collocano o ordinano eventi passati."),
  ],
  "b1-second-conditional": [
    q("Distanza dalla realtà · Quale frase presenta il cambio di lavoro come ipotetico, non come piano già deciso?", ["If I changed jobs, I would look for a smaller company.", "If I change jobs, I will look for a smaller company.", "When I change jobs, I am going to choose a smaller company.", "I changed jobs, so I looked for a smaller company."], 0, "If I changed jobs, I would look for a smaller company. usa il second conditional e mantiene il cambio sul piano ipotetico."),
  ],
  "b1-passive-processes": [
    q("Sequenza di processo · Quale descrizione mantiene la stessa prospettiva impersonale in entrambe le fasi?", ["The samples are labelled before they are stored.", "The technicians label the samples before they store them.", "The samples are labelled before the technicians store them.", "The technicians label the samples before they are stored."], 0, "The samples are labelled before they are stored. usa due passive coerenti per descrivere il processo."),
  ],
  "b1-reported-speech": [
    q("Cambio di prospettiva · On Monday, Sara said, ‘I will send it tomorrow.’ Quale frase conserva il messaggio se lo riferisci il martedì?", ["Sara said that she would send it the following day.", "Sara says that she will send it tomorrow.", "Sara said that she had sent it the previous day.", "Sara told me that she was sending it the day before."], 0, "Sara said that she would send it the following day. adatta tempo verbale e riferimento temporale senza cambiare il contenuto."),
  ],
  "b1-relative-clauses": [
    q("Informazione essenziale · Ci sono più ingegneri: quale frase identifica precisamente quello che ha progettato il sistema?", ["The engineer who designed the system is here.", "The engineer, who designed the system, is here.", "The engineer whose team designed the system is here.", "The engineer who tested the system is here."], 0, "Senza virgole, who designed the system identifica quale ingegnere; con le virgole aggiungerebbe un'informazione non restrittiva."),
    q("Possesso · Quale relativa afferma che il progetto appartiene al designer che sta parlando?", ["The designer whose project won is speaking.", "The designer who led the winning project is speaking.", "The designer for whom the project was developed is speaking.", "The designer who spoke after the project won is speaking."], 0, "Whose esprime possesso: il progetto appartiene al designer."),
  ],
  "b1-long-listening-media": [
    q("Comprensione globale · Il servizio cita un dato positivo, due limiti e una prova ancora in corso. Quale sintesi evita di esagerare?", ["The initial result is encouraging, but the evidence is not yet sufficient for a final conclusion.", "The positive figure probably outweighs the two limitations, so the trial can already be considered successful.", "The two limitations make the positive figure less reliable, although they do not necessarily invalidate it.", "The ongoing trial should confirm whether the initial result is representative, but the available evidence already supports a firm conclusion."], 0, "The initial result is encouraging, but the evidence is not yet sufficient for a final conclusion. integra dato e limiti senza trasformare un risultato iniziale in una conclusione definitiva."),
  ],
  "b2-third-conditional": [
    q("Controfattuale passato · Quale frase attribuisce l'esito a una condizione che non si è verificata?", ["If the team had checked the figures, it would have detected the error.", "If the team checked the figures, it would detect the error now.", "If the team checks the figures, it will detect the error.", "Because the team checked the figures, it detected the error."], 0, "If the team had checked the figures, it would have detected the error. descrive una condizione passata irreale e la sua conseguenza mancata."),
  ],
  "b2-reported-speech": [
    q("Distanza temporale · She said, ‘I am waiting.’ Quale resa conserva lo stesso contenuto da un punto di vista passato?", ["She said that she was waiting.", "She says that she is waiting.", "She said that she had finished waiting.", "She said that she would wait later."], 0, "She said that she was waiting. mantiene l'azione in corso e applica il normale backshift."),
    q("Prospettiva · ‘I will call you tomorrow,’ he said on Monday. Quale versione conserva persona e tempo se la riferisci il martedì?", ["He said that he would call me the following day.", "He says that he will call you tomorrow.", "He said that he had called me the previous day.", "He told me that he was calling someone that Monday."], 0, "He said that he would call me the following day. adatta will, you e tomorrow alla nuova prospettiva."),
    q("Reporting verb · Quale frase usa tell con l'oggetto personale richiesto?", ["She told me that the meeting had moved.", "She said that the meeting had moved.", "She explained that the meeting had moved.", "She mentioned that the meeting had moved."], 0, "She told me that the meeting had moved. è l'unica alternativa costruita con tell e il suo oggetto personale."),
  ],
  "b2-relative-gerund": [
    q("Gerundio o infinito · Quale frase presenta il rinvio come proposta, non come decisione, intenzione o necessità?", ["I suggest postponing the launch.", "I have decided to postpone the launch.", "I intend to postpone the launch.", "I need to postpone the launch."], 0, "I suggest postponing the launch. usa suggest + gerundio e mantiene il rinvio sul piano della proposta."),
    q("Cambio di significato · Quale frase significa che l'attività è stata interrotta?", ["He stopped working at six.", "He stopped to work at six.", "He remembered working at six.", "He tried working at six."], 0, "Stop + -ing significa cessare l'attività; stop + to indica fermarsi per fare altro."),
    q("Relativa restrittiva · Quale frase limita l'intervista soltanto ai candidati che soddisfano i criteri?", ["Candidates who meet the criteria will be interviewed.", "The candidates, who meet the criteria, will be interviewed.", "The candidates will be interviewed, having met the criteria.", "All candidates will be interviewed after the criteria are reviewed."], 0, "Candidates who meet the criteria will be interviewed. usa una relativa senza virgole per restringere il gruppo."),
  ],
  "b2-spoken-nuance": [
    q("Implicatura · ‘That deadline is rather ambitious’ detto in riunione comunica più probabilmente che:", ["the speaker doubts the deadline is realistic without rejecting it directly", "the speaker guarantees the deadline will be met ahead of schedule", "the speaker has no opinion about feasibility or timing", "the speaker believes ambition is unrelated to the proposed deadline"], 0, "The speaker doubts the deadline is realistic without rejecting it directly: rather ambitious può funzionare come critica attenuata."),
  ],
  "b2-inference-compromise": [
    q("Compromesso · Quale proposta accoglie il principio ma limita il rischio?", ["We can launch in one region, provided that results are reviewed daily.", "We can launch everywhere because monitoring is unnecessary.", "We should reject the launch before examining any evidence.", "We can monitor results without defining any action threshold."], 0, "La prima proposta combina avanzamento, condizione verificabile e controllo del rischio."),
  ],
  "b2-final-mission": [
    q("Inferenza prudente · Quale conclusione resta compatibile con prove incomplete?", ["The delay may have been caused by the missing figures.", "The delay must have been caused by the missing figures.", "The delay cannot have been caused by the missing figures.", "The delay should have been prevented despite the missing figures."], 0, "May have been caused esprime un'inferenza possibile senza trasformarla in certezza."),
    q("Priorità temporale · Quale frase presenta il controllo come già concluso prima della decisione?", ["The team had reviewed the evidence before it approved the change.", "The team reviewed the evidence after it had approved the change.", "The team was reviewing the evidence when it approved the change.", "The team has reviewed the evidence since it approved the change."], 0, "Past Perfect segnala che la revisione era già conclusa prima dell'approvazione."),
  ],
  "b2-mixed-conditionals": [
    q("Causa passata, effetto presente · Quale frase collega una decisione non presa ieri alla situazione attuale?", ["If we had accepted the offer, we would be working in Berlin now.", "If we accepted the offer, we would have worked in Berlin yesterday.", "If we had accepted the offer, we would have worked in Berlin before then.", "If we accept the offer, we will have worked in Berlin now."], 0, "If we had accepted the offer, we would be working in Berlin now. combina condizione passata irreale ed effetto presente."),
  ],
  "b2-modal-deduction": [
    q("Grado di certezza · Le luci sono spente e nessuno risponde, ma non hai prove definitive. Quale deduzione è proporzionata?", ["They might have left already.", "They must have left already.", "They cannot have left already.", "They should have left already."], 0, "They might have left already. esprime una possibilità compatibile con indizi non conclusivi."),
  ],
  "b2-causative-passive": [
    q("Responsabilità esterna · Quale frase indica che abbiamo incaricato qualcun altro di eseguire il lavoro?", ["We had the equipment repaired.", "We repaired the equipment ourselves.", "We had repaired the equipment before the inspection.", "We were repairing the equipment when the technician arrived."], 0, "We had the equipment repaired. usa la struttura causativa e attribuisce l'esecuzione a un'altra persona."),
  ],
  "b2-negotiation": [
    q("Concessione diplomatica · Quale risposta riconosce il vantaggio ma introduce una riserva concreta?", ["I can see the benefit; however, we would need a clear exit clause.", "I can see the benefit, so no safeguards or conditions are necessary.", "I reject the benefit because discussing an exit clause is impossible.", "I accept every condition, although I have not considered the proposal."], 0, "I can see the benefit; however, we would need a clear exit clause. combina riconoscimento e riserva negoziabile."),
  ],
  "b2-slang-phrasal": [
    q("Registro · Quale frase è adatta a una conversazione informale ma non a un rapporto formale?", ["I was absolutely knackered after the shift.", "I experienced considerable fatigue after the shift.", "The shift resulted in substantial physical fatigue.", "I was moderately tired following the scheduled shift."], 0, "Knackered è molto informale e tipicamente britannico; le altre formulazioni sono neutre o formali."),
    q("Esito · The agreement fell through. Quale implicazione è corretta?", ["The agreement was planned but did not happen.", "The agreement was signed but implemented later than expected.", "The agreement was revised before both parties approved it.", "The agreement remained valid despite a difficult negotiation."], 0, "Fall through significa non concretizzarsi."),
    q("Implicazione · Calling the plan a long shot comunica che:", ["success is possible but unlikely", "success is likely if the current plan is followed", "success depends mainly on how quickly the plan begins", "success has become more likely after an earlier attempt"], 0, "A long shot è un tentativo con possibilità di successo ridotte, non impossibili."),
  ],
  "b2-uk-us-english": [
    q("Coerenza · Quale frase mantiene interamente l'uso britannico?", ["I've just moved into a flat near the city centre.", "I just moved into an apartment near the city centre.", "I've just moved into an apartment near downtown centre.", "I just moved into a flat near downtown."], 0, "Present Perfect con just, flat e city centre formano una combinazione coerentemente britannica."),
    q("Piani · Un americano dice first floor. Quale rischio deve evitare un britannico?", ["Assumere che indichi necessariamente il piano sopra il livello strada.", "Assumere che indichi necessariamente il livello strada anche nell'uso britannico.", "Assumere che first floor e ground floor siano intercambiabili in ogni paese.", "Assumere che il numero del piano sia chiaro senza confermare il punto d'incontro."], 0, "Negli Stati Uniti first floor è normalmente il livello strada; in UK corrisponde al ground floor."),
    q("Varietà · Quale conclusione è linguisticamente corretta?", ["UK e US English sono varietà corrette, ma nello scritto conviene mantenere coerenza.", "UK English è l'unica varietà grammaticalmente corretta in ogni contesto internazionale.", "US English è l'unica varietà adatta alla comunicazione professionale internazionale.", "UK e US English differiscono soltanto nella pronuncia, non nel lessico o nella grammatica."], 0, "UK e US English sono varietà corrette, ma nello scritto conviene mantenere coerenza: differiscono anche in lessico, ortografia e alcuni usi grammaticali."),
  ],
  "c1-inversion-emphasis": [
    q("Enfasi · Quale frase porta Never in posizione iniziale e applica l'inversione richiesta?", ["Never have I seen such a rapid change.", "I have never seen such a rapid change.", "Only later did I see how rapid the change was.", "Rarely do we witness such a rapid change.", "Not until then did I recognise the rapid change."], 0, "Never have I seen such a rapid change. è l'unica alternativa che combina proprio Never iniziale e inversione."),
  ],
  "c1-hedging-stance": [
    q("Prudenza argomentativa · Quale conclusione riconosce un beneficio possibile senza presentarlo come dimostrato?", ["The findings suggest a possible benefit, although the evidence remains limited.", "The findings conclusively prove a benefit, although no evidence is available.", "The findings may prove with absolute certainty that the benefit is universal.", "The findings are too limited to support even a tentative interpretation.", "The findings guarantee a benefit despite the unresolved limitations."], 0, "The findings suggest a possible benefit, although the evidence remains limited. calibra la conclusione con suggest, possible e although."),
  ],
  "c1-cleft-structures": [
    q("Focus contrastivo · Quale cleft corregge l'idea che il costo, e non il tempo, abbia causato il rifiuto?", ["It was the delay that made them reject the proposal.", "It was the proposal that they rejected because of the delay.", "What they rejected after the delay was the proposal.", "What caused the rejection was the cost, not the delay.", "The reason they rejected the proposal was its cost."], 0, "It was the delay that made them reject the proposal. concentra il contrasto su the delay e corregge l'alternativa the cost."),
  ],
  "c1-nominalisation": [
    q("Nominalizzazione · Quale versione conserva chiaramente chi ha deciso e che cosa è stato deciso?", ["The committee's decision to postpone the launch prompted further review.", "The decision to postpone the launch prompted further review, but the decision-maker is not identified.", "The launch postponement prompted further review, while responsibility for it remains unspecified.", "Further review followed the postponement, although the text does not identify who authorised it.", "The committee reviewed the postponement after an unidentified decision had been made."], 0, "The committee's decision to postpone the launch prompted further review. nominalizza decide in decision senza oscurare agente e contenuto."),
    q("Focus informativo · Che effetto produce normalmente la nominalizzazione in un testo formale?", ["Sposta il focus dall'azione o dall'agente al processo, al risultato o al concetto.", "Mantiene il focus sull'agente, ma rende il verbo più prudente e meno diretto.", "Sposta il focus sul momento preciso in cui si svolge l'azione, chiarendone soprattutto il tempo verbale.", "Rende il processo più concreto e personale, mettendo in primo piano chi lo compie.", "Sostituisce una relazione logica esplicita con una forma più colloquiale e narrativa."], 0, "Sposta il focus dall'azione o dall'agente al processo, al risultato o al concetto. È utile, ma può anche nascondere l'agente se usata male."),
    q("Densità controllata · Quale frase è formale e concisa senza accumulare nominalizzazioni inutili?", ["The rapid expansion of the service increased demand for support.", "The rapid expansion of the service resulted in an increase in demand for the provision of support.", "Following the service's rapid expansion, an increase in demand for support provision was observed.", "The service's rapid expansion was associated with an increase in the level of demand for support.", "An increase in support demand occurred subsequent to the rapid expansion of the service."], 0, "The rapid expansion of the service increased demand for support. mantiene un registro formale con un verbo chiaro e meno sostantivi astratti."),
  ],
  "c1-discourse-cohesion": [
    q("Relazione logica · The first trial reduced costs; ___, it increased waiting times. Quale connettivo esprime correttamente il contrasto concessivo?", ["however", "therefore", "moreover", "similarly", "consequently"], 0, "However segnala che l'aumento dei tempi contrasta con il vantaggio economico appena presentato."),
    q("Coesione · Quale sequenza esprime prima una concessione, poi un contrasto e infine una conseguenza?", ["Admittedly, the sample was small. Nevertheless, the pattern was consistent; therefore, further testing was justified.", "The sample was small. Similarly, the pattern was consistent; moreover, further testing was justified.", "The sample was small. Consequently, the pattern was consistent; nevertheless, further testing was justified.", "Admittedly, the sample was small. Therefore, the pattern was consistent; however, further testing was justified.", "The sample was small. In other words, the pattern was consistent; similarly, further testing was justified."], 0, "Admittedly, the sample was small. Nevertheless, the pattern was consistent; therefore, further testing was justified. realizza nell'ordine concessione, contrasto e conseguenza."),
    q("Contrasto preciso · Quale frase confronta due risultati senza suggerire che uno abbia causato l'altro?", ["Whereas the urban sample improved, the rural sample remained stable.", "Therefore the urban sample improved, the rural sample remained stable.", "Consequently the urban sample improved, the rural sample remained stable.", "Because the urban sample improved, the rural sample remained stable.", "Thus the urban sample improved, the rural sample remained stable."], 0, "Whereas the urban sample improved, the rural sample remained stable. esprime contrasto, non causalità."),
  ],
  "c1-rhetoric-media": [
    q("Inquadramento retorico · Un titolo definisce una riduzione temporanea ‘a collapse’. Quale analisi è più precisa?", ["The wording amplifies the scale and permanence of the change beyond what the evidence establishes.", "The wording neutrally reports the measured reduction without adding any evaluative frame.", "The wording proves that the reduction is permanent because collapse is a technical statistic.", "The wording weakens the event by presenting the reduction as less important than the data suggest.", "The wording removes all emotional connotations and limits the claim to the observation period."], 0, "The wording amplifies the scale and permanence of the change beyond what the evidence establishes. distingue il dato dalla cornice retorica."),
  ],
  "c1-idiom-register": [
    q("Registro · Quale riscrittura conserva il significato di ‘The proposal doesn't quite cut it’ in un rapporto formale?", ["The proposal does not fully meet the required standard.", "The proposal narrowly meets the standard despite minor reservations.", "The proposal exceeds the required standard in several respects.", "The proposal meets the standard but requires clearer presentation.", "The proposal cannot yet be assessed against the required standard."], 0, "The proposal does not fully meet the required standard. conserva l'insufficienza espressa dall'idioma senza mantenerne il registro colloquiale."),
  ],
  "c1-uk-us-nuance": [
    q("Piani · Un collega statunitense propone di incontrarsi on the first floor. Qual è la risposta più sicura in un team internazionale?", ["Confirm whether they mean the street-level floor, because first floor differs between US and UK usage.", "Assume they mean the floor above street level, because that meaning is universal.", "Assume they mean the street-level floor, because British usage is irrelevant internationally.", "Ask whether first refers to the first room rather than to a level of the building.", "Replace floor with storey without confirming the physical meeting point."], 0, "Confirm whether they mean the street-level floor, because first floor differs between US and UK usage. evita un'inferenza culturale non condivisa."),
    q("Accordo · Quale osservazione descrive correttamente team is e team are?", ["Both can occur: singular agreement is especially common in US English, while plural agreement is more available in UK English when members are emphasised.", "Both can occur, but team are is especially common in US English, while team is is preferred in UK English when the members are emphasised.", "Both can occur in UK and US English with no meaningful difference in regional preference or in how the group is viewed.", "Team is normally presents the members individually, whereas team are presents the team as one unit.", "Team are is available only when the sentence explicitly lists at least two individual members of the team."], 0, "Both can occur: singular agreement is especially common in US English, while plural agreement is more available in UK English when members are emphasised."),
    q("Ambiguità internazionale · Quale formulazione riduce meglio il rischio di interpretare diversamente una data?", ["The deadline is 5 April 2027.", "The deadline is 05/04/27.", "The deadline is 04/05/27.", "The deadline is next 05/04.", "The deadline is spring 27."], 0, "The deadline is 5 April 2027. scrive il mese in lettere e l'anno per esteso, evitando l'inversione giorno-mese."),
  ],
  "c1-diplomatic-negotiation": [
    q("Condizione negoziale · Quale frase esprime disponibilità senza comunicare un'approvazione definitiva?", ["We could endorse the proposal, subject to an independent review.", "We endorse the proposal unconditionally and no further review is required.", "We might have endorsed the proposal before the review was cancelled.", "We reject the proposal unless our endorsement has already been recorded.", "We will endorse every proposal regardless of the independent review."], 0, "We could endorse the proposal, subject to an independent review. rende l'adesione possibile ma subordinata a una verifica."),
  ],
  "c1-academic-argument": [
    q("Struttura argomentativa · In ‘Remote work may improve retention because greater flexibility reduces commuting pressure’, quale parte funge da warrant?", ["The assumption that reducing commuting pressure can help employees remain in a job.", "The claim that remote work may improve retention, considered as the conclusion to be supported.", "The observation that greater flexibility reduces commuting pressure, considered as the stated supporting reason.", "The caution expressed by may, which limits how confidently the conclusion is presented.", "The implied comparison between remote and office work, regardless of its connection to employee retention."], 0, "The assumption that reducing commuting pressure can help employees remain in a job. collega la ragione alla conclusione e funziona da warrant."),
    q("Forza della prova · Quale frase distingue correttamente associazione e spiegazione causale?", ["The variables are associated, but the design does not establish that one caused the other.", "The variables are associated, so the first necessarily caused the second.", "The variables are associated, which proves that no third factor was involved.", "The variables are associated only if the effect is universal and permanent.", "The variables are associated, therefore the causal direction is already known."], 0, "The variables are associated, but the design does not establish that one caused the other. evita di trasformare correlazione in causalità."),
    q("Limite metodologico · Quale conclusione è proporzionata a un campione piccolo e non rappresentativo?", ["The result is suggestive rather than conclusive and should be tested in a broader sample.", "The result conclusively represents the entire population despite the sampling limitation.", "The result is necessarily false because a small sample can never provide useful evidence.", "The result proves the opposite conclusion because representativeness was not demonstrated.", "The result guarantees replication as long as the same small sample is reused."], 0, "The result is suggestive rather than conclusive and should be tested in a broader sample. riconosce sia il segnale sia il limite."),
  ],
  "c1-long-documentary": [
    q("Inferenza · Il narratore descrive investimenti sospesi e personale trasferito, ma non annuncia la chiusura. Quale conclusione è più rigorosa?", ["The project appears to be losing priority, although closure is not explicitly confirmed.", "The project has definitely closed because staff movement always proves permanent closure.", "The project is certainly expanding because suspended investment indicates rapid growth.", "The project cannot have changed because the narrator did not use the word closure.", "The project was legally dissolved before any staff were transferred."], 0, "The project appears to be losing priority, although closure is not explicitly confirmed. distingue l'inferenza dagli elementi dichiarati."),
  ],
  "c1-synthesis-capstone": [
    q("Sintesi · Quale frase integra due fonti invece di riassumerle una dopo l'altra?", ["Both studies link flexibility to retention, but only the longitudinal study indicates that the effect persists over time.", "The first study discusses flexibility. The second study discusses retention.", "Study A comes first in the report, and Study B is described on the following page.", "The studies contain several paragraphs, each followed by a separate bibliography.", "The first study is longer than the second, so its conclusion must be more reliable."], 0, "Both studies link flexibility to retention, but only the longitudinal study indicates that the effect persists over time. combina convergenza e differenza in un'unica relazione."),
    q("Divergenza · Due fonti concordano sul problema ma propongono cause diverse. Quale frase lo rappresenta con precisione?", ["The sources agree that participation declined, yet they attribute the decline to different factors.", "The sources disagree that participation declined and identify exactly the same causal factor.", "The sources agree on every causal detail but report opposite participation trends.", "The sources provide unrelated evidence, so no comparison of their explanations is possible.", "The sources prove that every proposed factor caused the decline to the same extent."], 0, "The sources agree that participation declined, yet they attribute the decline to different factors. separa la convergenza sul dato dalla divergenza causale."),
    q("Conclusione integrata · Quale formulazione sintetizza prove convergenti senza cancellare un limite condiviso?", ["Taken together, the studies support a modest effect, although neither resolves the question of long-term durability.", "Taken together, the studies prove a permanent effect because both report at least one positive result.", "Taken together, the studies cancel each other's findings because both mention a methodological limitation.", "Taken together, the studies establish that durability is irrelevant to interpreting the reported effect.", "Taken together, the studies guarantee identical outcomes in every population and time period."], 0, "Taken together, the studies support a modest effect, although neither resolves the question of long-term durability. integra accordo e limite senza sovrastimare le prove."),
  ],
};
