"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {curriculumIndex,mobileCurriculum,type Choice,type MobileUnit} from "./curriculum";

type View="home"|"path"|"lesson"|"progress"; type Phase="grammar"|"examples"|"cloze"|"writing"|"listening"|"speaking"|"quiz"|"complete";
type Result={score:number;attempts:number;minutes:number;completedAt?:string;writing?:string};
type Progress={deviceId:string;currentDay:number;streak:number;lastStudyDate?:string;days:Record<string,Result>;activity:Record<string,{minutes:number;score:number;completed:number}>};
type RecCtor=new()=>{lang:string;interimResults:boolean;continuous:boolean;start():void;onresult:((e:{results:ArrayLike<{0:{transcript:string}}>})=>void)|null;onerror:(()=>void)|null;onend:(()=>void)|null};
declare global{interface Window{SpeechRecognition?:RecCtor;webkitSpeechRecognition?:RecCtor}}
const stages:Phase[]=["grammar","examples","cloze","writing","listening","speaking","quiz"];
const labels:Record<Phase,string>={grammar:"Grammatica",examples:"Esempi",cloze:"Completa",writing:"Scrivi",listening:"Ascolta",speaking:"Ripeti",quiz:"Quiz",complete:"Completata"};
const dateKey=()=>new Date().toISOString().slice(0,10);
const fresh=(id:string):Progress=>({deviceId:id,currentDay:1,streak:0,days:{},activity:{}});
const validCode=(v:string)=>/^[A-Za-z0-9-]{12,80}$/.test(v);
function deviceId(){const k="english-coach-device-id",old=localStorage.getItem(k);if(old)return old;const id=crypto.randomUUID?.()??`coach-${Date.now()}-${Math.random().toString(36).slice(2)}`;localStorage.setItem(k,id);return id}
function similarity(a:string,b:string){const words=(s:string)=>s.toLowerCase().replace(/[^\p{L}\p{N}\s']/gu,"").split(/\s+/).filter(Boolean),x=words(a),y=words(b);return x.length?Math.round(x.filter(w=>y.includes(w)).length/x.length*100):0}
function AudioButton({text,src,label="Ascolta"}:{text:string;src?:string;label?:string}){const[on,setOn]=useState(false);const speak=()=>{if(!speechSynthesis)return;const voices=speechSynthesis.getVoices().filter(v=>/^en(?:-|$)/i.test(v.lang)),voice=voices.find(v=>/^en-GB/i.test(v.lang))??voices[0];if(!voice)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.voice=voice;u.lang=voice.lang;u.rate=.9;u.onstart=()=>setOn(true);u.onend=u.onerror=()=>setOn(false);speechSynthesis.speak(u)};const play=()=>{if(!src)return speak();const a=new Audio(src);a.onplay=()=>setOn(true);a.onended=()=>setOn(false);a.onerror=()=>{setOn(false);speak()};a.play().catch(speak)};return <button className="audio" onClick={play}><b>{on?"■":"▶"}</b>{on?"In ascolto…":label}</button>}
function Question({data,done}:{data:Choice;done:(ok:boolean)=>void}){const[pick,setPick]=useState<number|null>(null);return <div className="question"><h3>{data.prompt}</h3><div className="answers">{data.options.map((x,i)=><button key={x+i} disabled={pick!==null} className={pick===null?"":i===data.answer?"right":i===pick?"wrong":"dim"} onClick={()=>{setPick(i);done(i===data.answer)}}><b>{String.fromCharCode(65+i)}</b>{x}</button>)}</div>{pick!==null&&<div className={`feedback ${pick===data.answer?"good":"bad"}`}><strong>{pick===data.answer?"Esatto!":"Quasi."}</strong><p>{data.explanationIt}</p></div>}</div>}
function Gauge({value}:{value:number}){const v=Math.max(0,Math.min(100,value));return <section className="gaugeCard"><div className="gauge"><i/><em style={{transform:`rotate(${-90+v*1.8}deg)`}}/><b/></div><strong>{v}</strong><span>Indice di apprendimento</span><small>{v>=80?"Ottimo ritmo":v>=55?"Stai crescendo":"Ogni passo conta"}. Non è un voto.</small></section>}
export default function Home(){
 const[view,setView]=useState<View>("home"),[progress,setProgress]=useState<Progress|null>(null),[unit,setUnit]=useState<MobileUnit>(mobileCurriculum[0]),[phase,setPhase]=useState<Phase>("grammar"),[item,setItem]=useState(0),[input,setInput]=useState(""),[checked,setChecked]=useState<boolean|null>(null),[writing,setWriting]=useState(""),[answered,setAnswered]=useState<boolean|null>(null),[points,setPoints]=useState({yes:0,all:0}),[spoken,setSpoken]=useState(""),[recording,setRecording]=useState(false),[sync,setSync]=useState<"saved"|"saving"|"offline">("saved"),[recover,setRecover]=useState(""),[recoverMsg,setRecoverMsg]=useState("");const started=useRef(Date.now());
 const save=async(p:Progress)=>{setSync("saving");localStorage.setItem("english-coach-progress-v2",JSON.stringify(p));setSync("offline")};

 useEffect(()=>{const id=deviceId();let p=fresh(id);try{p={...p,...JSON.parse(localStorage.getItem("english-coach-progress-v2")||"{}"),deviceId:id}}catch{}setProgress(p);setSync("offline")},[]);
 const[writingNotes,setWritingNotes]=useState<string[]|null>(null);
 const completed=progress?Object.keys(progress.days).length:0,average=useMemo(()=>!progress||!completed?0:Math.round(Object.values(progress.days).reduce((s,d)=>s+d.score,0)/completed),[progress,completed]),performance=completed?Math.round(average*.75+Math.min(completed,24)*1.04):0;
 const clear=()=>{setItem(0);setInput("");setChecked(null);setAnswered(null);setSpoken("")};
 const open=(u:MobileUnit)=>{setUnit(u);setPhase("grammar");setWriting(progress?.days[u.day]?.writing||"");setPoints({yes:0,all:0});clear();started.current=Date.now();setView("lesson");scrollTo(0,0)};
 const nextPhase=()=>{setPhase(stages[stages.indexOf(phase)+1]??"complete");clear();scrollTo(0,0)};
 const score=(ok:boolean)=>{if(answered!==null)return;setAnswered(ok);setPoints(p=>({yes:p.yes+(ok?1:0),all:p.all+1}))};
 const advance=(n:number)=>item+1<n?(setItem(i=>i+1),setInput(""),setChecked(null),setAnswered(null)):nextPhase();
 const check=()=>{const ok=unit.writing.cloze[item].answers.some(x=>x.trim().toLowerCase()===input.trim().toLowerCase());setChecked(ok);setPoints(p=>({yes:p.yes+(ok?1:0),all:p.all+1}))};
 const finish=async()=>{if(!progress)return;const score=points.all?Math.round(points.yes/points.all*100):100,today=dateKey(),y=new Date();y.setDate(y.getDate()-1);const streak=progress.lastStudyDate===today?progress.streak:progress.lastStudyDate===y.toISOString().slice(0,10)?progress.streak+1:1,minutes=Math.max(1,Math.round((Date.now()-started.current)/60000)),old=progress.activity[today]??{minutes:0,score:0,completed:0};const p:Progress={...progress,currentDay:Math.min(24,Math.max(progress.currentDay,unit.day+1)),streak,lastStudyDate:today,days:{...progress.days,[unit.day]:{score,attempts:(progress.days[unit.day]?.attempts||0)+1,minutes,writing,completedAt:new Date().toISOString()}},activity:{...progress.activity,[today]:{minutes:old.minutes+minutes,score:old.completed?Math.round((old.score+score)/2):score,completed:old.completed+1}}};setProgress(p);await save(p);setPhase("complete")};
 const analyzeWriting=()=>{const t=writing.trim(),notes:string[]=[];if(t&&!/^[A-Z]/.test(t))notes.push("Inizia il testo con una lettera maiuscola.");if(t&&!/[.!?]$/.test(t))notes.push("Concludi la frase finale con punto, punto interrogativo o esclamativo.");if(/\b(he|she|it)\s+(work|live|speak|need|want|like|start|finish)\b/i.test(t))notes.push("Con he, she o it, al Present Simple aggiungi normalmente -s al verbo.");if(/\bdid\s+\w+(ed|went|saw|took)\b/i.test(t))notes.push("Dopo did usa il verbo base: did go, non did went.");if(/\bI am agree\b/i.test(t))notes.push("Si dice I agree, senza am.");if(/\bpeople is\b/i.test(t))notes.push("People è plurale: usa people are.");const target=unit.grammar.formulas[0]?.split(/[.:;]/)[0]?.trim();if(target&&target.length>2&&!t.toLowerCase().includes(target.toLowerCase().split(" ")[0]))notes.push(`Rileggi la struttura della lezione: ${unit.grammar.formulas[0]}`);if(!notes.length)notes.push("Ottimo controllo: non vedo errori di base. Rileggi comunque il significato ad alta voce.");setWritingNotes(notes)};
 const record=()=>{const R=window.SpeechRecognition??window.webkitSpeechRecognition;if(!R){setSpoken("Riconoscimento vocale non disponibile in questo browser.");return}const r=new R();r.lang="en-GB";r.interimResults=false;r.continuous=false;setRecording(true);r.onresult=e=>{setSpoken(e.results[0][0].transcript);setRecording(false)};r.onerror=()=>{setSpoken("Non ho sentito bene. Riprova.");setRecording(false)};r.onend=()=>setRecording(false);r.start()};
 const recoverProgress=async()=>{if(!validCode(recover)){setRecoverMsg("Usa da 12 a 80 lettere, numeri o trattini.");return}setRecoverMsg("Il salvataggio è locale su questo telefono. La sincronizzazione tra dispositivi non è attiva.")};
 if(!progress)return <main className="loading"><span className="logo">EC</span><p>Preparo il percorso…</p></main>;
 const current=mobileCurriculum.find(x=>x.day===progress.currentDay)??mobileCurriculum.at(-1)!;
 return <main className="app">
  <header><button className="brand" onClick={()=>setView("home")}><span className="logo">EC</span><span><strong>English Coach</strong><small>Un passo al giorno</small></span></button><span className={`sync ${sync}`}>{sync==="saved"?"Online · salvato":sync==="saving"?"Salvataggio…":"Salvato sul telefono"}</span></header>
  {view==="home"&&<div className="screen"><section className="hero"><div><span className="eyebrow">Giorno {current.day} · {current.cefr}</span><h1>{current.title}</h1><p>Impara una regola, usala e trasformala in inglese parlato.</p></div><aside><b>{completed}/24</b><small>completati</small></aside></section><button className="start" onClick={()=>open(current)}><span><strong>Inizia l’allenamento</strong><small>{current.minutes} min · 7 tappe guidate</small></span><b>→</b></button><div className="stats"><article><span>🔥</span><b>{progress.streak}</b><small>giorni di ritmo</small></article><article><span>◎</span><b>{average?`${average}%`:"—"}</b><small>precisione media</small></article><article><span>✓</span><b>{completed}</b><small>unità concluse</small></article></div><section className="card"><div className="title"><div><span className="eyebrow">La sessione di oggi</span><h2>Breve, completa, concreta</h2></div><i>{current.minutes} min</i></div><div className="flow">{stages.map((s,i)=><div key={s}><b>{i+1}</b><small>{labels[s]}</small></div>)}</div></section><aside className="tip">💡 <span><b>Consiglio gentile</b>Meglio 18 minuti ogni giorno che una sessione lunga ogni tanto.</span></aside></div>}
  {view==="path"&&<div className="screen"><div className="pageTitle"><span className="eyebrow">Da A1 a B2</span><h1>Il tuo percorso</h1><p>24 tappe progressive. Puoi sempre rivedere una lezione svolta.</p></div>{(["A1","A2","B1","B2"] as const).map(level=><section className="level" key={level}><div className="levelTitle"><b>{level}</b><span><h2>{level==="A1"?"Fondamenta":level==="A2"?"Autonomia":level==="B1"?"Situazioni reali":"Padronanza"}</h2><p>{curriculumIndex.levels[level].goalIt}</p></span></div><div className="units">{mobileCurriculum.filter(x=>x.cefr===level).map(u=>{const done=progress.days[u.day],locked=u.day>progress.currentDay;return <button key={u.id} disabled={locked} className={done?"done":u.day===progress.currentDay?"current":""} onClick={()=>!locked&&open(u)}><b>{done?"✓":locked?"·":u.day}</b><span><strong>{u.title}</strong><small>Giorno {u.day} · {u.minutes} min{done?` · ${done.score}%`:""}</small></span><i>{locked?"🔒":"›"}</i></button>})}</div></section>)}</div>}
  {view==="progress"&&<div className="screen"><div className="pageTitle"><span className="eyebrow">La tua crescita</span><h1>Progressi</h1><p>Uno sguardo sereno alla costanza, non una classifica.</p></div><Gauge value={performance}/><div className="metrics"><article><span>Media</span><b>{average?`${average}%`:"—"}</b><small>attività completate</small></article><article><span>Ritmo</span><b>{progress.streak} gg</b><small>continuità attuale</small></article></div><section className="card"><div className="title"><div><span className="eyebrow">Ultimi 7 giorni</span><h2>La tua presenza</h2></div></div><div className="week">{Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));const k=d.toISOString().slice(0,10),a=progress.activity[k];return <div key={k}><i className={a?"active":""} style={{height:`${a?Math.max(20,Math.min(100,a.minutes*5)):8}%`}}/><small>{d.toLocaleDateString("it-IT",{weekday:"narrow"})}</small></div>})}</div></section><section className="card recovery"><span className="eyebrow">Codice recupero</span><h2>I progressi ti seguono</h2><p>Questo è il tuo codice personale. Copialo per continuare su un altro telefono.</p><code>{progress.deviceId}</code><button onClick={()=>{navigator.clipboard.writeText(progress.deviceId);setRecoverMsg("Codice copiato.")}}>Copia codice</button><label>Recupera un profilo esistente<input value={recover} onChange={e=>setRecover(e.target.value)} placeholder="Incolla il codice personale"/></label><button className="outline" onClick={recoverProgress}>Recupera progressi</button>{recoverMsg&&<small role="status">{recoverMsg}</small>}<em>✓ Dati sincronizzati online quando la connessione è disponibile.</em></section></div>}
  {view==="lesson"&&<div className="lesson"><div className="lessonTop"><button onClick={()=>setView("home")}>×</button><div><i style={{width:`${((stages.indexOf(phase)+1)/stages.length)*100}%`}}/></div><b>{unit.cefr}</b></div><article className="lessonCard"><span className="eyebrow">{phase==="complete"?"Sessione conclusa":labels[phase]}</span>
   {phase==="grammar"&&<><h1>{unit.title}</h1><p className="intro">Prima capiamo la regola, poi la userai subito.</p><div className="explain">{unit.grammar.explanationIt.map((x,i)=><div key={x}><b>{i+1}</b><p>{x}</p></div>)}</div><div className="formula"><small>FORMULA RAPIDA</small>{unit.grammar.formulas.map(x=><code key={x}>{x}</code>)}</div><button className="continue" onClick={nextPhase}>Guarda gli esempi <b>→</b></button></>}
   {phase==="examples"&&<><h1>La regola in azione</h1><p className="intro">Ascolta l’inglese, poi confronta il significato.</p><div className="examples">{unit.grammar.examples.map(x=><div key={x.en}><AudioButton text={x.en}/><strong lang="en">{x.en}</strong><span>{x.it}</span><p>{x.noteIt}</p></div>)}</div><button className="continue" onClick={nextPhase}>Prova tu <b>→</b></button></>}
   {phase==="cloze"&&<><small className="count">Domanda {item+1} di {unit.writing.cloze.length}</small><h1>Completa la frase</h1><p className="prompt" lang="en">{unit.writing.cloze[item].prompt}</p><label className="field">La parola mancante<input value={input} disabled={checked!==null} onChange={e=>setInput(e.target.value)} autoCapitalize="none"/></label>{checked!==null&&<div className={`feedback ${checked?"good":"bad"}`}><b>{checked?"Perfetto!":"Rivediamola insieme."}</b><p>{unit.writing.cloze[item].hintIt}{!checked&&<> Risposta: <strong>{unit.writing.cloze[item].answers[0]}</strong>.</>}</p></div>}<button className="continue" disabled={!input.trim()} onClick={()=>checked===null?check():advance(unit.writing.cloze.length)}>{checked===null?"Verifica":item+1<unit.writing.cloze.length?"Prossima":"Continua"}<b>→</b></button></>}
   {phase==="writing"&&<><h1>Scrivi con parole tue</h1><p className="intro">{unit.writing.productionPromptIt}</p><label className="field">La tua risposta in inglese<textarea rows={7} lang="en" value={writing} onChange={e=>{setWriting(e.target.value);setWritingNotes(null)}} placeholder="Scrivi qui…"/><small>{writing.trim()?writing.trim().split(/\s+/).length:0} parole</small></label><button className="writingCheck" disabled={writing.trim().split(/\s+/).filter(Boolean).length<4} onClick={analyzeWriting}>Controlla il testo</button>{writingNotes&&<div className="checklist"><b>Correzione guidata</b>{writingNotes.map(x=><span key={x}>✓ {x}</span>)}</div>}<button className="continue" disabled={!writingNotes} onClick={nextPhase}>Vai all’ascolto <b>→</b></button></>}
   {phase==="listening"&&<><small className="count">Domanda {item+1} di {unit.listening.questions.length}</small><h1>Ascolta e comprendi</h1><p className="intro">{unit.listening.guideIt}</p><div className="player"><AudioButton text={unit.listening.transcript} src={`${import.meta.env.BASE_URL}audio/${unit.id}-listening.wav`} label="Riproduci dialogo"/><small>Voce inglese madrelingua · puoi riascoltare</small></div><Question key={`l${item}`} data={unit.listening.questions[item]} done={score}/><button className="continue" disabled={answered===null} onClick={()=>advance(unit.listening.questions.length)}>{item+1<unit.listening.questions.length?"Prossima":"Continua"}<b>→</b></button></>}
   {phase==="speaking"&&<><h1>Listen and repeat</h1><p className="intro">{unit.speaking.promptIt}</p><div className="repeat"><AudioButton text={unit.speaking.target} src={`${import.meta.env.BASE_URL}audio/${unit.id}-speaking.wav`} label="Ascolta la frase"/><blockquote lang="en">{unit.speaking.target}</blockquote><div>{unit.speaking.focus.map(x=><small key={x}>{x}</small>)}</div></div><button className={`record ${recording?"on":""}`} onClick={record}>● {recording?"Ti ascolto…":"Parla in inglese"}</button>{spoken&&<div className="speech"><small>HO CAPITO</small><p lang="en">“{spoken}”</p>{!spoken.startsWith("Riconoscimento")&&!spoken.startsWith("Non ho")&&<b>{similarity(unit.speaking.target,spoken)}% di parole riconosciute</b>}</div>}<button className="continue" onClick={nextPhase}>Vai al quiz <b>→</b></button></>}
   {phase==="quiz"&&<><small className="count">Domanda {item+1} di {unit.quickCheck.length}</small><h1>Controllo finale</h1><Question key={`q${item}`} data={unit.quickCheck[item]} done={score}/><button className="continue" disabled={answered===null} onClick={()=>item+1<unit.quickCheck.length?advance(unit.quickCheck.length):finish()}>{item+1<unit.quickCheck.length?"Prossima":"Concludi"}<b>→</b></button></>}
   {phase==="complete"&&<div className="complete"><div>✓</div><h1>Allenamento completato!</h1><p>Hai studiato, scritto, ascoltato e parlato. È così che l’inglese diventa tuo.</p><strong>{points.all?Math.round(points.yes/points.all*100):100}%</strong><small>precisione di oggi</small><em>Sotto l’80%? Nessun problema: ripetere consolida la memoria.</em><button className="continue" onClick={()=>setView("home")}>Torna alla home <b>→</b></button></div>}
  </article></div>}
  {view!=="lesson"&&<nav><button className={view==="home"?"active":""} onClick={()=>setView("home")}><b>⌂</b>Oggi</button><button className={view==="path"?"active":""} onClick={()=>setView("path")}><b>◇</b>Percorso</button><button className={view==="progress"?"active":""} onClick={()=>setView("progress")}><b>↗</b>Progressi</button></nav>}
 </main>
}




