import type { Cefr } from "./curriculum";
import type { HangmanEntry } from "./wordGames";

export type AntonymEntry = { left: string; right: string; group: string };

export const extraHangman: Record<Cefr, HangmanEntry[]> = {
  A1: [
    { phrase: "THE SHOP IS OPEN TODAY", hint: "Say that customers can enter the shop today." },
    { phrase: "MY ROOM IS SMALL BUT BRIGHT", hint: "Describe a room using two simple adjectives." },
    { phrase: "WE HAVE BREAKFAST AT SEVEN", hint: "Describe the time of a daily meal." },
    { phrase: "TURN LEFT AT THE BANK", hint: "Give a simple direction near a bank." },
    { phrase: "THE KEYS ARE UNDER THE CHAIR", hint: "Say where the keys are." },
    { phrase: "I NEED A GLASS OF WATER", hint: "Ask for something to drink." },
    { phrase: "THE BUS STOP IS OVER THERE", hint: "Point out the place where a bus stops." },
    { phrase: "HE WORKS IN A SMALL OFFICE", hint: "Describe a man's workplace." },
    { phrase: "WE DO NOT EAT MEAT", hint: "Make a simple negative statement about food." },
    { phrase: "HOW MUCH IS THIS TICKET", hint: "Ask the price of a ticket." },
  ],
  A2: [
    { phrase: "I HAVE ALREADY BOOKED THE HOTEL", hint: "A completed booking that matters now." },
    { phrase: "THE FILM WAS BETTER THAN I EXPECTED", hint: "Compare a film with your expectation." },
    { phrase: "COULD YOU SHOW ME THE WAY", hint: "A polite request for directions." },
    { phrase: "SHE HAS WORKED HERE FOR TWO YEARS", hint: "An action continuing for a duration." },
    { phrase: "WE MIGHT GO TO THE BEACH TOMORROW", hint: "Express an uncertain plan." },
    { phrase: "THE ROOM WAS CLEANED THIS MORNING", hint: "A simple passive sentence about a room." },
    { phrase: "I FORGOT TO SEND THE MESSAGE", hint: "Describe a task you did not remember." },
    { phrase: "THERE WERE TOO MANY PEOPLE", hint: "Describe a crowded place in the past." },
    { phrase: "YOU SHOULD TRY THE LOCAL FOOD", hint: "Give advice to a visitor." },
    { phrase: "WHEN I ARRIVED THEY WERE EATING", hint: "A past action already in progress." },
  ],
  B1: [
    { phrase: "THE FLIGHT WAS CANCELLED DUE TO FOG", hint: "Explain why a flight did not leave." },
    { phrase: "I WISH I HAD MORE FREE TIME", hint: "Express dissatisfaction with the present." },
    { phrase: "SHE REMINDED ME TO LOCK THE DOOR", hint: "Report a reminder about security." },
    { phrase: "THE PROBLEM TURNED OUT TO BE SIMPLE", hint: "The final reality was easier than expected." },
    { phrase: "WE HAVE NOT MADE A DECISION YET", hint: "A decision is still pending." },
    { phrase: "HE MANAGED TO SOLVE THE ISSUE", hint: "Describe a successful difficult action." },
    { phrase: "THE PRODUCT IS MADE FROM RECYCLED PLASTIC", hint: "A passive description of material." },
    { phrase: "I WOULD RATHER STAY AT HOME", hint: "Express a preference for this evening." },
    { phrase: "THEY APOLOGISED FOR ARRIVING LATE", hint: "Use apologise followed by the correct preposition." },
    { phrase: "UNLESS WE HURRY WE WILL MISS THE TRAIN", hint: "A condition with a negative meaning." },
  ],
  B2: [
    { phrase: "THE EVIDENCE DOES NOT SUPPORT THAT CONCLUSION", hint: "Challenge a conclusion by referring to evidence." },
    { phrase: "THE CONTRACT SHOULD HAVE BEEN REVIEWED EARLIER", hint: "Criticise a missed past obligation in the passive." },
    { phrase: "WERE IT NOT FOR HER HELP WE WOULD HAVE FAILED", hint: "A formal inverted condition about essential help." },
    { phrase: "THE BENEFITS OUTWEIGH THE POTENTIAL DRAWBACKS", hint: "Conclude that advantages are more important." },
    { phrase: "HE DENIED HAVING DISCLOSED THE INFORMATION", hint: "Report a denial about an earlier action." },
    { phrase: "THE RESULTS ARE CONSISTENT WITH OUR INITIAL FORECAST", hint: "Compare results with an earlier prediction." },
    { phrase: "THE MEASURE IS INTENDED TO REDUCE INEQUALITY", hint: "Explain the purpose of a policy in the passive." },
    { phrase: "MUCH OF THE DAMAGE COULD HAVE BEEN PREVENTED", hint: "A modal passive about an avoidable past outcome." },
    { phrase: "THE ARGUMENT OVERLOOKS A CRUCIAL DISTINCTION", hint: "Identify an important detail missing from an argument." },
    { phrase: "ONLY AFTERWARDS DID WE REALISE THE FULL IMPACT", hint: "Use inversion after a restrictive time expression." },
  ],
  C1: [
    { phrase: "THE FINDINGS WARRANT A MORE CAUTIOUS INTERPRETATION", hint: "Recommend restraint when interpreting research." },
    { phrase: "THE APPARENT CONSENSUS MASKS SUBSTANTIAL DISAGREEMENT", hint: "A surface agreement hides deeper conflict." },
    { phrase: "HIS ACCOUNT IS INTERNALLY COHERENT YET EMPIRICALLY WEAK", hint: "Contrast logical consistency with poor evidence." },
    { phrase: "THE PROPOSAL IS CONTINGENT ON SECURING ADEQUATE FUNDING", hint: "Funding is a necessary condition for the proposal." },
    { phrase: "SCARCELY HAD THE DEBATE ENDED WHEN NEW EVIDENCE EMERGED", hint: "Formal inversion for two closely timed events." },
    { phrase: "THE AUTHOR TACITLY CONCEDES THE LIMITS OF THE MODEL", hint: "Describe an indirect admission of limitations." },
    { phrase: "THE DISTINCTION MAY BE VALID BUT IT IS NOT EXHAUSTIVE", hint: "Accept a distinction while limiting its scope." },
    { phrase: "THE POLICY RISKS EXACERBATING THE VERY PROBLEM IT TARGETS", hint: "A policy may worsen the issue it aims to solve." },
    { phrase: "NOTWITHSTANDING THESE RESERVATIONS THE FRAMEWORK REMAINS USEFUL", hint: "A formal concession before a positive conclusion." },
    { phrase: "THE CLAIM IS PLAUSIBLE ONLY UNDER A NARROW SET OF ASSUMPTIONS", hint: "Limit a claim to specific underlying conditions." },
  ],
};

export const antonymSets: Record<Cefr, AntonymEntry[]> = {
  A1: [
    { left: "big", right: "small", group: "size" }, { left: "long", right: "short", group: "size" },
    { left: "wide", right: "narrow", group: "size" }, { left: "high", right: "low", group: "size" },
    { left: "heavy", right: "light", group: "size" }, { left: "hot", right: "cold", group: "daily" },
    { left: "clean", right: "dirty", group: "daily" }, { left: "open", right: "closed", group: "daily" },
    { left: "early", right: "late", group: "daily" }, { left: "fast", right: "slow", group: "daily" },
    { left: "happy", right: "sad", group: "people" }, { left: "young", right: "old", group: "people" },
    { left: "strong", right: "weak", group: "people" }, { left: "kind", right: "unkind", group: "people" },
    { left: "awake", right: "asleep", group: "people" },
  ],
  A2: [
    { left: "cheap", right: "expensive", group: "shopping" }, { left: "buy", right: "sell", group: "shopping" },
    { left: "borrow", right: "lend", group: "shopping" }, { left: "save", right: "spend", group: "shopping" },
    { left: "available", right: "unavailable", group: "shopping" }, { left: "arrive", right: "depart", group: "travel" },
    { left: "enter", right: "exit", group: "travel" }, { left: "near", right: "far", group: "travel" },
    { left: "upstairs", right: "downstairs", group: "travel" }, { left: "domestic", right: "international", group: "travel" },
    { left: "accept", right: "refuse", group: "actions" }, { left: "remember", right: "forget", group: "actions" },
    { left: "include", right: "exclude", group: "actions" }, { left: "increase", right: "decrease", group: "actions" },
    { left: "connect", right: "disconnect", group: "actions" },
  ],
  B1: [
    { left: "advantage", right: "disadvantage", group: "decisions" }, { left: "success", right: "failure", group: "decisions" },
    { left: "approve", right: "reject", group: "decisions" }, { left: "encourage", right: "discourage", group: "decisions" },
    { left: "improve", right: "worsen", group: "decisions" }, { left: "confident", right: "insecure", group: "attitude" },
    { left: "patient", right: "impatient", group: "attitude" }, { left: "generous", right: "selfish", group: "attitude" },
    { left: "polite", right: "rude", group: "attitude" }, { left: "reliable", right: "unreliable", group: "attitude" },
    { left: "temporary", right: "permanent", group: "change" }, { left: "expand", right: "contract", group: "change" },
    { left: "permit", right: "forbid", group: "change" }, { left: "reveal", right: "conceal", group: "change" },
    { left: "gain", right: "lose", group: "change" },
  ],
  B2: [
    { left: "scarce", right: "abundant", group: "resources" }, { left: "adequate", right: "insufficient", group: "resources" },
    { left: "sustainable", right: "unsustainable", group: "resources" }, { left: "efficient", right: "wasteful", group: "resources" },
    { left: "surplus", right: "shortage", group: "resources" }, { left: "explicit", right: "implicit", group: "arguments" },
    { left: "objective", right: "subjective", group: "arguments" }, { left: "relevant", right: "irrelevant", group: "arguments" },
    { left: "coherent", right: "inconsistent", group: "arguments" }, { left: "valid", right: "invalid", group: "arguments" },
    { left: "compulsory", right: "optional", group: "policy" }, { left: "transparent", right: "opaque", group: "policy" },
    { left: "centralised", right: "decentralised", group: "policy" }, { left: "restrict", right: "liberalise", group: "policy" },
    { left: "comply", right: "violate", group: "policy" },
  ],
  C1: [
    { left: "converge", right: "diverge", group: "analysis" }, { left: "substantiate", right: "refute", group: "analysis" },
    { left: "corroborate", right: "contradict", group: "analysis" }, { left: "clarify", right: "obfuscate", group: "analysis" },
    { left: "bolster", right: "undermine", group: "analysis" }, { left: "unequivocal", right: "ambiguous", group: "stance" },
    { left: "impartial", right: "biased", group: "stance" }, { left: "forthright", right: "evasive", group: "stance" },
    { left: "tentative", right: "definitive", group: "stance" }, { left: "conciliatory", right: "confrontational", group: "stance" },
    { left: "exacerbate", right: "alleviate", group: "outcomes" }, { left: "deteriorate", right: "ameliorate", group: "outcomes" },
    { left: "proliferate", right: "diminish", group: "outcomes" }, { left: "relinquish", right: "retain", group: "outcomes" },
    { left: "transient", right: "enduring", group: "outcomes" },
  ],
};
