import type { Cefr } from "./curriculum";

export type NaturalReplyQuestion = {
  situationIt: string;
  prompt: string;
  options: string[];
  answer: number;
  explanationIt: string;
};

const q = (situationIt: string, prompt: string, options: string[], answer: number, explanationIt: string): NaturalReplyQuestion => ({ situationIt, prompt, options, answer, explanationIt });

export const naturalReplies: Record<Cefr, NaturalReplyQuestion[]> = {
  A1: [
    q("Incontri una persona per la prima volta.", "Hi, I'm Emma. Nice to meet you.", ["Nice to meet you too.", "See you yesterday.", "I'm meeting fine."], 0, "Nice to meet you too è la risposta naturale quando ci si presenta."),
    q("Al bar ti chiedono cosa desideri.", "What would you like?", ["I'd like a tea, please.", "I like yesterday.", "Tea is liking me."], 0, "I'd like ... please serve per ordinare in modo semplice e cortese."),
    q("Un collega ti ringrazia.", "Thanks for your help.", ["You're welcome.", "I welcome you.", "Please thank."], 0, "You're welcome è la risposta abituale a un ringraziamento."),
    q("Non senti bene una domanda.", "What's your phone number?", ["Sorry, can you repeat that?", "No, I repeat you.", "What phone is number?"], 0, "Sorry, can you repeat that? chiede gentilmente di ripetere."),
    q("Qualcuno ti offre dell'acqua.", "Would you like some water?", ["Yes, please.", "Yes, I like water yesterday.", "Please, I am water."], 0, "Yes, please accetta cortesemente un'offerta."),
    q("Devi salutare e andare via.", "Are you leaving now?", ["Yes. See you tomorrow.", "Yes. I see yesterday.", "Tomorrow was goodbye."], 0, "See you tomorrow è un saluto naturale prima di andare via."),
    q("Chiedi dove si trova la stazione.", "Can I help you?", ["Yes, where is the station?", "Yes, where the station is?", "Yes, station where?"], 0, "Where is the station? usa l'ordine corretto della domanda."),
    q("Un amico ti chiede come stai.", "How are you today?", ["I'm fine, thanks. And you?", "I have fine today.", "I am how, thanks."], 0, "I'm fine, thanks. And you? risponde e ricambia la domanda."),
    q("In negozio non vuoi acquistare subito.", "Would you like to buy it?", ["No, thanks. I'm just looking.", "No, I look just.", "No, I am seeing only."], 0, "I'm just looking è la frase comune per dire che stai soltanto guardando."),
    q("Non conosci l'ora.", "Excuse me, what time is it?", ["It's half past three.", "It has three and half.", "They are half three."], 0, "It's half past three è la costruzione corretta per indicare l'ora."),
  ],
  A2: [
    q("Vuoi chiedere un favore a un collega.", "Could you send me the address?", ["Of course. I'll send it now.", "I could send yesterday.", "Of course, I am send it."], 0, "Of course. I'll send it now accetta la richiesta e indica l'azione futura."),
    q("Arrivi in ritardo a un appuntamento.", "We've been waiting for twenty minutes.", ["I'm really sorry I'm late.", "I regret you wait.", "I am sorry for wait you."], 0, "I'm really sorry I'm late è una scusa diretta e naturale."),
    q("Un amico propone il cinema, ma hai già un impegno.", "Shall we go to the cinema tonight?", ["I'd love to, but I'm busy tonight.", "I love, but I was busy tomorrow.", "I prefer not cinema ever."], 0, "I'd love to, but ... rifiuta con cortesia spiegando il motivo."),
    q("In hotel la camera è troppo rumorosa.", "Is everything all right with your room?", ["Actually, it's quite noisy. Could I change rooms?", "Actually, noise makes room.", "I change because it has noisy."], 0, "Actually introduce con tatto il problema; Could I ...? formula una richiesta cortese."),
    q("Non sei sicuro del programma del fine settimana.", "Are you coming with us on Saturday?", ["I'm not sure yet. I'll let you know tomorrow.", "I don't know already yesterday.", "I tell you when I decided before."], 0, "I'm not sure yet e I'll let you know sono espressioni naturali per un piano non deciso."),
    q("Hai perso l'autobus e spieghi perché sei in ritardo.", "What happened?", ["I missed the bus, so I had to wait for the next one.", "I lost the bus and must waited.", "The bus missed me for waiting."], 0, "Miss the bus significa non riuscire a prenderlo; had to descrive la conseguenza passata."),
    q("In un negozio vuoi una taglia diversa.", "Does this jacket fit?", ["It's a bit tight. Have you got a larger size?", "It fits too little. Is there more large?", "It is narrow. Give biggest."], 0, "A bit tight e a larger size sono le espressioni naturali nel contesto."),
    q("Un collega ti invita a pranzo.", "Would you like to join us for lunch?", ["That sounds great. What time are you going?", "That hears great. When do you go yesterday?", "I join perhaps at lunching."], 0, "That sounds great accetta la proposta; la domanda successiva chiede il dettaglio utile."),
    q("Chiedi consiglio su un posto da visitare.", "How long are you staying in Edinburgh?", ["Three days. What do you recommend seeing?", "Three days. What I must see you?", "I stay since three days tomorrow."], 0, "What do you recommend seeing? è una richiesta naturale di consiglio."),
    q("Qualcuno non ha capito le indicazioni.", "Sorry, which street did you say?", ["King Street. It's the second road on the left.", "King Street. It was left two street.", "King Street. You turn in second roads."], 0, "Second road on the left dà un'indicazione chiara con la struttura corretta."),
  ],
  B1: [
    q("Un collega propone una scadenza difficile da rispettare.", "Can you finish the report by Friday morning?", ["I can try, but I may need until the afternoon.", "I try, although Friday finished it.", "I will possibly finish since the afternoon.", "I can finish unless I need Friday."], 0, "I can try, but ... segnala disponibilità e limite senza promettere troppo."),
    q("Ricevi un reclamo per un ordine arrivato danneggiato.", "The package arrived with two broken items.", ["I'm sorry about that. I'll arrange a replacement straight away.", "You should have opened it more carefully.", "Broken items are usually arriving.", "I regret, but the package was your problem."], 0, "La risposta riconosce il problema, si scusa e propone subito una soluzione concreta."),
    q("Non condividi del tutto un'opinione durante una riunione.", "Remote work always makes teams less productive.", ["I'm not sure I entirely agree; it depends on how the team is organised.", "No, you're completely wrong about everything.", "I don't agree because productivity is productive.", "Yes, but I disagree without any reason."], 0, "I'm not sure I entirely agree introduce un disaccordo rispettoso e motivato."),
    q("Un amico racconta di non aver ottenuto un lavoro.", "They chose another candidate in the end.", ["I'm sorry to hear that. You must be disappointed.", "Never mind; the job was probably terrible.", "You should not have applied at all.", "I'm sorry that you disappointed them."], 0, "La risposta mostra empatia senza minimizzare o giudicare l'esperienza."),
    q("Devi chiarire un possibile equivoco.", "I thought you were presenting the first section.", ["I may have misunderstood. I thought you wanted me to do the conclusion.", "You definitely explained it badly.", "I misunderstand because you will present it.", "The conclusion thought it was mine."], 0, "I may have misunderstood prende responsabilità con prudenza e chiarisce l'interpretazione."),
    q("Vuoi interrompere educatamente per chiedere un chiarimento.", "So the figures rose by twelve per cent in the final quarter...", ["Sorry to interrupt, but does that include online sales?", "Stop. What are online sales?", "I interrupt you because figures include?", "Before you speak, the figures are unclear."], 0, "Sorry to interrupt, but ... è una formula cortese; la domanda è specifica."),
    q("Un ristorante non può servire il piatto scelto.", "I'm afraid we've run out of the seafood pasta.", ["That's a shame. What would you recommend instead?", "Then you must cook it anyway.", "I am afraid too because pasta ran.", "Give me whichever thing without asking."], 0, "That's a shame reagisce naturalmente; What would you recommend instead? cerca un'alternativa."),
    q("Ti chiedono un aggiornamento su un problema tecnico.", "Has the login issue been fixed?", ["Not yet, but the technical team is looking into it.", "No, it didn't fix since now.", "The issue looks the technical team.", "Not yet, so nobody is doing nothing."], 0, "Not yet indica che il problema continua; is looking into it comunica l'azione in corso."),
    q("Vuoi verificare di aver capito una consegna.", "Please send the revised version before the client call.", ["Just to confirm, you need it by ten tomorrow morning, right?", "Confirm me when the client calls before.", "You need yesterday's version after ten, correct?", "I send it unless the call was revised."], 0, "Just to confirm ... right? controlla scadenza e aspettativa senza ambiguità."),
    q("Non puoi accettare subito una proposta economica.", "Can we agree on the price today?", ["I'd like some time to think it over before I decide.", "I think over it since I decide now.", "The price agrees, but I don't.", "I will decide before thinking it."], 0, "Think it over significa valutare con attenzione prima di decidere."),
  ],
  B2: [
    q("In riunione riconosci un vantaggio, ma segnali un rischio.", "This plan would reduce costs significantly.", ["That's a fair point, although we should also consider the impact on quality.", "Costs matter, whereas quality is never relevant.", "I concede costs and therefore reject the plan entirely.", "That's correct, despite I don't consider quality."], 0, "That's a fair point concede il vantaggio; although introduce una riserva pertinente."),
    q("Un cliente formula una richiesta non prevista dal contratto.", "We assumed weekend support was included.", ["I can see how that misunderstanding arose. Let me clarify what the current agreement covers.", "You assumed wrongly, so there is nothing to discuss.", "Weekend support is excluded because assumptions are invalid.", "I clarify that you must have read the contract better."], 0, "La risposta riconosce l'equivoco senza attribuire colpe e propone un chiarimento concreto."),
    q("Devi correggere con tatto un dato presentato da un collega.", "Sales increased by twenty per cent last quarter.", ["If I'm reading the table correctly, that figure refers to revenue rather than sales volume.", "No, the table clearly proves you cannot read figures.", "The figure is incorrect because revenue and sales are identical.", "I read correctly; therefore your twenty per cent is false."], 0, "If I'm reading ... correctly attenua la correzione e distingue con precisione i due indicatori."),
    q("Ti chiedono una decisione prima che siano disponibili tutti i dati.", "Should we approve the proposal now?", ["I'd rather reserve judgement until we've seen the full cost breakdown.", "I refuse to judge because proposals require no evidence.", "We might approve it, although the costs are certainly irrelevant.", "I'd rather we approve it before seeing the figures."], 0, "Reserve judgement significa sospendere la valutazione finché non arrivano prove sufficienti."),
    q("Una persona interpreta il tuo silenzio come accordo.", "Nobody objected, so I assumed everyone supported the change.", ["I wouldn't necessarily infer agreement from the absence of objections.", "Silence invariably demonstrates unanimous support.", "I didn't object, despite I had explicitly agreed.", "The absence of objections implies that nobody heard you."], 0, "La risposta distingue prudentemente tra assenza di obiezioni e consenso reale."),
    q("Devi rifiutare una soluzione che risolve solo una parte del problema.", "This workaround should stop the immediate errors.", ["It may address the symptoms, but it doesn't tackle the underlying cause.", "It solves the cause, even though only the symptoms remain solved.", "Immediate errors are the underlying cause by definition.", "It may work, so investigating further would be pointless."], 0, "La risposta concede l'effetto immediato ma distingue sintomo e causa strutturale."),
    q("Un collega presenta come certo un risultato ancora preliminare.", "The pilot proves that customers prefer the new design.", ["The findings are encouraging, but the sample is too small to support that conclusion yet.", "The result is preliminary, so it proves the conclusion beyond doubt.", "Customers certainly prefer it because a pilot cannot be misleading.", "The sample is small; nevertheless no further evidence is required."], 0, "Encouraging riconosce il segnale positivo, mentre la seconda parte limita correttamente la conclusione."),
    q("Vuoi riportare la discussione al punto principale.", "We've spent twenty minutes discussing the colour of the slides.", ["Could we step back and focus on the decision we need to make today?", "Could we step down and decide why colours are decisions?", "Let's continue, since the main decision can remain indefinitely unclear.", "The colour issue makes every other point beside the question."], 0, "Step back and focus on ... riporta con tatto la conversazione alla priorità."),
    q("Un fornitore promette una consegna, ma resta vago.", "We should be able to deliver fairly soon.", ["Could you give me a specific date so that we can plan accordingly?", "Soon is specific enough for all operational planning.", "Could you deliver vaguely, provided that dates are unnecessary?", "I need a date, although please don't tell me when."], 0, "La risposta trasforma un impegno vago in una richiesta misurabile e motivata."),
    q("Riconosci che una critica è in parte fondata.", "The report doesn't explain how the estimates were calculated.", ["That's a valid criticism. We should make the methodology more transparent.", "The criticism is valid, but the methodology must remain less clear.", "Estimates never require an explanation, so the criticism is irrelevant.", "Transparency would undermine the report because readers might understand it."], 0, "La risposta accetta il punto specifico e propone una correzione coerente."),
  ],
  C1: [
    q("Durante una discussione complessa vuoi contestare una conclusione senza negare i dati.", "The figures are accurate, so the policy has clearly succeeded.", ["I don't dispute the figures; I question whether they warrant such a broad conclusion.", "The figures are accurate, which renders every interpretation equally conclusive.", "I dispute neither the conclusion nor the assumption that no interpretation is needed.", "The policy succeeded insofar as accurate figures invariably prove causation.", "I reject the figures precisely because I accept their accuracy."], 0, "La risposta distingue correttamente l'accuratezza dei dati dalla portata dell'inferenza."),
    q("Vuoi mediare tra due posizioni presentate come incompatibili.", "Either we prioritise speed or we maintain rigorous oversight.", ["That may be a false dichotomy; the real question is which safeguards can operate without causing unnecessary delay.", "The alternatives are mutually exclusive because oversight and speed can never coexist.", "We should choose both without examining how either would be implemented.", "Rigour necessarily precludes efficiency, notwithstanding any evidence to the contrary.", "The dichotomy is false solely because neither objective is worth pursuing."], 0, "La risposta identifica la falsa dicotomia e riformula il problema in termini operativi."),
    q("Devi esprimere una riserva formale su una proposta promettente.", "The framework could substantially improve consistency across departments.", ["Its potential is clear, though its effectiveness will depend on how consistently it is implemented.", "Its potential guarantees effectiveness irrespective of implementation.", "The framework is consistent, albeit implementation has no bearing on outcomes.", "It might improve consistency; hence any reservations would be self-contradictory.", "Its effectiveness is clear precisely because implementation remains unspecified."], 0, "La risposta riconosce il potenziale ma rende esplicita una condizione decisiva."),
    q("Un interlocutore attribuisce intenzioni che il testo non dimostra.", "The author omits the counterargument because she wants to mislead readers.", ["The omission is significant, but attributing intent would require evidence the text doesn't provide.", "The omission conclusively establishes a deliberate intention to deceive.", "Intent is irrelevant, therefore the omission has no analytical significance.", "The text provides no evidence, which paradoxically confirms the author's motive.", "Any omitted counterargument must be interpreted as intentional manipulation."], 0, "La risposta separa un limite osservabile dall'attribuzione non dimostrata di intenzione."),
    q("Devi chiedere una precisazione su un termine ambiguo.", "The reform will make the process more efficient.", ["Could you clarify what you mean by efficient and how you intend to measure it?", "Efficiency is self-evident, so defining it would only obscure the discussion.", "Could you confirm that efficient necessarily means cheaper in every respect?", "I understand efficient to mean successful, measurable or otherwise.", "How efficient is efficiency when the process reforms efficiently?"], 0, "La domanda definisce il termine operativo e chiede un criterio di misurazione."),
    q("Riconosci un'obiezione valida senza abbandonare la tua tesi.", "Your recommendation could place a disproportionate burden on smaller firms.", ["That's a legitimate concern, and it suggests the measure may need a scaled implementation rather than outright rejection.", "The concern is legitimate, which means the recommendation has no defensible element.", "Smaller firms face a burden; nevertheless proportionality is beside the point.", "The objection is valid only if we disregard the possibility of any adaptation.", "A disproportionate burden confirms that uniform implementation is the only fair option."], 0, "La risposta integra l'obiezione nella proposta attraverso un'applicazione proporzionata."),
    q("Vuoi segnalare che una spiegazione è plausibile ma non esclusiva.", "The decline was caused by the change in pricing.", ["Pricing may have contributed, but the evidence doesn't rule out other factors.", "Pricing is plausible and therefore excludes every competing explanation.", "Other factors are possible, which proves pricing played no role whatsoever.", "The evidence is inconclusive, so no factor may be discussed as contributory.", "Pricing caused the decline unless several causes operated simultaneously."], 0, "May have contributed mantiene l'ipotesi; doesn't rule out evita di trasformarla nell'unica causa."),
    q("Devi sintetizzare un disaccordo tra criteri diversi.", "We keep debating which option is objectively best.", ["We may be applying different criteria: one side prioritises reliability, while the other gives greater weight to flexibility.", "The disagreement proves that neither side is using any identifiable criterion.", "Objectivity requires everyone to assign identical weight to every consideration.", "Reliability and flexibility are interchangeable criteria, hence the debate is merely verbal.", "Different priorities make a reasoned comparison logically impossible."], 0, "La risposta rende espliciti i criteri concorrenti e chiarisce la vera origine del disaccordo."),
    q("Vuoi evitare che un'eccezione venga trasformata in una regola generale.", "This approach worked in one department, so we should adopt it everywhere.", ["The result is worth examining, but we should establish whether the conditions are comparable before generalising.", "One successful case is sufficient to establish universal applicability.", "Generalisation is justified provided that no comparison between contexts is attempted.", "The departments differ, which means the successful result has no informational value.", "We should adopt it everywhere precisely because the relevant conditions remain unknown."], 0, "La risposta valorizza il caso positivo ma richiede comparabilità prima di generalizzare."),
    q("Devi chiudere una riunione con un accordo ancora condizionato.", "Can we say that the committee has approved the proposal?", ["We have agreement in principle, subject to the revised budget being circulated and accepted.", "The proposal is unconditionally approved, provided that a decisive condition is later rejected.", "Agreement in principle means the remaining budget issue is purely irrelevant.", "The committee has approved the budget, although neither the budget nor the proposal was discussed.", "We can announce final approval while explicitly withholding any form of agreement."], 0, "Agreement in principle, subject to ... comunica correttamente un consenso non ancora definitivo."),
  ],
};

export const naturalReplyIsCorrect = (question: NaturalReplyQuestion, choice: number) => choice === question.answer;
