import type { Choice } from "./curriculum";
import type { ThemePack, ThemeWord } from "./themePacks";

const q = (prompt: string, options: string[], answer: number, explanationIt: string): Choice => ({ prompt, options, answer, explanationIt });
const words = (rows: [string, string, string][]): ThemeWord[] => rows.map(([en, it, example]) => ({ en, it, example }));

export const professionalThemePacks: ThemePack[] = [
  {
    id: "professional-a1-workday", category: "professional", level: "A1", title: "Primo giorno di lavoro", minutes: 20, introducedIn: "7.8",
    summary: "Presentarti, dire il tuo ruolo, capire orari e chiedere aiuto con frasi semplici.",
    guide: ["I work in... indica il reparto o il settore.", "I am responsible for... introduce una responsabilità semplice.", "Could you help me? è una richiesta cortese.", "I start at... e I finish at... descrivono l’orario."],
    vocabulary: words([["colleague","collega","This is my colleague, Anna."],["department","reparto","I work in the sales department."],["shift","turno","My shift starts at nine."],["task","attività","This is my first task."],["manager","responsabile","My manager is in a meeting."],["break","pausa","The lunch break is at one."],["available","disponibile","I am available this afternoon."],["help","aiutare/aiuto","Could you help me, please?"]]),
    scenario: { title: "Meeting a new colleague", text: "Maya: Hi, I’m Maya. I work in customer service. Leo: Nice to meet you. I’m Leo, the team assistant. Maya: What time is the lunch break? Leo: It’s at one. I can show you the kitchen and the meeting room.", translation: "Maya e Leo si presentano. Leo spiega l’orario della pausa e offre un aiuto pratico." },
    questions: [q("Where does Maya work?",["In customer service","In the kitchen","In a bank"],0,"Maya dice: I work in customer service."),q("What is Leo’s role?",["Team assistant","Customer","Driver"],0,"Leo si presenta come team assistant."),q("What time is the lunch break?",["At one","At nine","At five"],0,"Leo dice: It’s at one."),q("What does Leo offer to do?",["Show Maya two rooms","Finish Maya’s shift","Call a customer"],0,"Leo offre di mostrarle la cucina e la sala riunioni.")]
  },
  {
    id: "professional-a2-email-update", category: "professional", level: "A2", title: "Email e aggiornamenti chiari", minutes: 25, introducedIn: "7.8",
    summary: "Confermare, chiedere informazioni e comunicare un piccolo ritardo senza risultare bruschi.",
    guide: ["I’m writing to... spiega subito lo scopo dell’email.", "Could you confirm...? formula una richiesta cortese.", "There is a delay significa che c’è un ritardo.", "I’ll send... by Friday indica una scadenza precisa."],
    vocabulary: words([["subject line","oggetto dell’email","Use a clear subject line."],["confirm","confermare","Please confirm the meeting time."],["attachment","allegato","The report is in the attachment."],["deadline","scadenza","The deadline is Friday."],["delay","ritardo","There is a short delay."],["update","aggiornamento","I will send an update tomorrow."],["available","disponibile","Are you available at three?"],["forward","inoltrare","Please forward the email to Marta."]]),
    scenario: { title: "A report will arrive one day late", text: "Subject: Report update. Hello Sam, I’m writing to update you about the monthly report. Two figures are still missing, so there is a short delay. I’ll send the complete report by Friday morning. Could you confirm that this new deadline is acceptable? Best regards, Nina.", translation: "Nina comunica il motivo del ritardo, dà una nuova scadenza precisa e chiede conferma." },
    questions: [q("Why is the report delayed?",["Two figures are missing","The meeting was cancelled","Nina is on holiday"],0,"Il messaggio collega il ritardo a due dati mancanti."),q("When will Nina send the report?",["By Friday morning","Next month","Before the missing figures arrive"],0,"La nuova scadenza è Friday morning."),q("What does Nina ask Sam to confirm?",["Whether the new deadline is acceptable","Whether the attachment is colourful","Whether the report should be deleted"],0,"Chiede se la nuova scadenza va bene."),q("Which subject line best matches the email?",["Report update","Hello!!!","An unrelated meeting"],0,"Report update rende immediato lo scopo.")]
  },
  {
    id: "professional-b1-meeting", category: "professional", level: "B1", title: "Riunione: aggiornare, proporre, riepilogare", minutes: 32, introducedIn: "7.8",
    summary: "Intervenire con chiarezza, distinguere fatti e proposte e chiudere con responsabilità precise.",
    guide: ["We’ve completed... aggiorna su un risultato rilevante ora.", "Could we...? introduce una proposta senza imporla.", "The main issue is... identifica il problema centrale.", "To sum up... riepiloga decisione, responsabile e scadenza."],
    vocabulary: words([["agenda","ordine del giorno","The budget is on today’s agenda."],["raise a point","sollevare un punto","Could I raise one point?"],["on schedule","nei tempi previsti","The project is on schedule."],["fall behind","restare indietro","Testing has fallen behind."],["action item","azione assegnata","This is my action item."],["follow up","dare seguito","I’ll follow up with the supplier."],["minutes","verbale","Please share the meeting minutes."],["to sum up","in sintesi","To sum up, Marta will call today."]]),
    scenario: { title: "A launch date at risk", text: "Marta: We’ve completed the new payment page, but accessibility testing has fallen behind. Paolo: Could we move the launch from Monday to Wednesday? That would give us two more days without changing the campaign. Marta: Agreed. To sum up, Paolo will complete the test by Tuesday noon, and I’ll update the client today.", translation: "Il gruppo separa il lavoro completato dal ritardo, propone un cambiamento limitato e assegna due azioni con scadenze." },
    questions: [q("Which work has been completed?",["The payment page","Accessibility testing","The client update","The campaign redesign"],0,"Il payment page è completo; il test è in ritardo."),q("Why is Wednesday proposed?",["It provides two more testing days","The campaign starts earlier","The client requested Monday","The payment page must be removed"],0,"Lo spostamento crea due giorni in più per il test."),q("What will Paolo do?",["Complete the accessibility test","Update the client","Change the campaign","Cancel the launch"],0,"Il riepilogo assegna a Paolo il test."),q("What makes the closing effective?",["It names owners and deadlines","It repeats the problem without a decision","It avoids assigning responsibility","It introduces a new unrelated topic"],0,"Il riepilogo definisce chi fa cosa e quando.")]
  },
  {
    id: "professional-b2-problem-solving", category: "professional", level: "B2", title: "Problemi, priorità e soluzioni verificabili", minutes: 38, introducedIn: "7.8",
    summary: "Gestire un problema professionale senza promesse premature, formulando opzioni e criteri di controllo.",
    guide: ["At this stage segnala che l’informazione è ancora provvisoria.", "The evidence suggests... distingue un dato da una certezza.", "Provided that introduce una condizione necessaria.", "A contingency plan definisce cosa fare se l’opzione principale fallisce."],
    vocabulary: words([["constraint","vincolo","Time is our main constraint."],["root cause","causa principale","We have not confirmed the root cause."],["workaround","soluzione temporanea","The team has a temporary workaround."],["contingency plan","piano alternativo","We need a contingency plan."],["provided that","a condizione che","We can proceed provided that testing passes."],["feasible","realizzabile","The revised schedule is feasible."],["escalate","portare a un livello superiore","Escalate the safety concern."],["mitigate","ridurre il rischio","This control may mitigate the risk."]]),
    scenario: { title: "A supplier delay threatens production", text: "The supplier can deliver the component on Thursday, two days later than planned. Production could still begin on Friday, provided that incoming inspection is completed before noon. The quality manager warns that this timetable leaves no margin for a failed check. The team therefore keeps the Friday slot but prepares a Monday contingency and asks the supplier for verified shipping data twice a day.", translation: "Il team mantiene l’opzione di venerdì solo con una condizione verificabile e prepara un’alternativa per lunedì." },
    questions: [q("What condition must be met for production to begin on Friday?",["Incoming inspection must finish before noon","The supplier must lower the price","Quality must skip the check","Production must start before delivery"],0,"Il venerdì dipende dal completamento dell’ispezione entro mezzogiorno."),q("Why does the quality manager remain concerned?",["There is no margin if the inspection fails","Monday is already impossible","The component has passed inspection","Shipping data cannot be verified"],0,"Il programma non assorbe un eventuale esito negativo."),q("What is the contingency?",["A production slot on Monday","Cancelling all future orders","Starting without the component","Replacing incoming inspection with an email"],0,"Il piano alternativo è lo slot del lunedì."),q("Which statement best describes the decision?",["Proceed conditionally while monitoring and preserving an alternative","Accept Friday as guaranteed","Reject the supplier without reviewing evidence","Transfer quality responsibility to the supplier"],0,"La decisione è condizionata, monitorata e accompagnata da un’alternativa.")]
  },
  {
    id: "professional-c1-negotiation", category: "professional", level: "C1", title: "Negoziazione e decisioni ad alta precisione", minutes: 45, introducedIn: "7.8",
    summary: "Interpretare concessioni, presupposti e formulazioni che sembrano simili ma producono obblighi diversi.",
    guide: ["Subject to approval indica che l’accordo non è ancora definitivo.", "Without prejudice consente di discutere senza rinunciare formalmente alla posizione corrente.", "A conditional concession offre un vantaggio in cambio di condizioni esplicite.", "Un riepilogo accurato separa punti concordati, questioni aperte e autorità necessarie."],
    vocabulary: words([["binding","vincolante","The draft is not legally binding."],["subject to","subordinato a","The offer is subject to board approval."],["without prejudice","senza pregiudicare la posizione","We can explore this without prejudice."],["conditional concession","concessione condizionata","The discount is a conditional concession."],["liability cap","limite di responsabilità","The liability cap remains unresolved."],["material change","modifica sostanziale","That wording is a material change."],["walk-away point","limite oltre il quale si rinuncia","Define the walk-away point in advance."],["outstanding issue","questione aperta","Two outstanding issues remain."]]),
    scenario: { title: "A discount tied to stronger commitments", text: "Supplier: Without prejudice to our current offer, we could reduce the annual fee by eight per cent, subject to a three-year term and payment within thirty days. Buyer: We could consider the longer term, provided that service thresholds become binding and repeated failure triggers termination. Supplier: The service clause is a material change and requires board approval. Let us record the pricing principle as provisionally aligned while keeping liability and termination open.", translation: "Le parti esplorano concessioni condizionate, ma l’accordo non è definitivo: autorizzazione, responsabilità e recesso restano aperti." },
    questions: [q("Which interpretation of the supplier’s first statement is most accurate?",["The discount depends on term and payment conditions","The discount is unconditional but the payment date is advisory","The current offer has already been withdrawn","The three-year term is optional after approval","Liability and termination are settled by the discount"],0,"La riduzione è esplicitamente subordinata a durata e pagamento."),q("Why is the buyer’s reply not an acceptance?",["It introduces binding service and termination conditions","It accepts every term while requesting a summary","It rejects the longer term categorically","It removes the need for approval","It merely asks when payment is due"],0,"La risposta introduce condizioni sostanziali nuove."),q("What remains only provisionally aligned?",["The pricing principle","The liability cap","The termination trigger","Board approval","All contractual language"],0,"Solo il principio economico viene registrato come provvisoriamente allineato."),q("What is the function of without prejudice here?",["It permits exploration without surrendering the current formal position","It makes the revised offer immediately binding","It waives the need for internal authority","It closes all outstanding issues","It guarantees acceptance of the counterproposal"],0,"La formula preserva la posizione mentre continua la discussione.")]
  }
];
