import type { Cefr } from "./curriculum";
export type DialogueOption = readonly [text:string, correct:0|1, consequence:string];
export type DialogueTurn = { prompt:string; options:DialogueOption[] };
const turn=(prompt:string,options:DialogueOption[]):DialogueTurn=>({prompt,options});
export const realDialogues:Record<Cefr,DialogueTurn[]>={
 A1:[
  turn("Al bar chiedono: ‘For here or to go?’",[["To go, please.",1,"Il barista capisce che vuoi portare via l’ordine."],["I go coffee.",0,"Il messaggio non chiarisce dove consumerai."],["Yes, I am.",0,"La risposta è grammaticale, ma non risponde alla scelta."]]),
  turn("Alla stazione: ‘The train now leaves from platform six.’",[["Thank you. Where is platform six?",1,"Confermi l’informazione e chiedi l’indicazione necessaria."],["The train is six.",0,"Six indica il binario, non il treno."],["I like the platform.",0,"La frase non aiuta a raggiungere il treno."]]),
  turn("In hotel chiedono: ‘Can I see your passport?’",[["Of course. Here it is.",1,"La procedura di check-in può continuare."],["My passport sees me.",0,"Soggetto e significato sono invertiti."],["I am a passport.",0,"La risposta cambia completamente il significato."]])],
 A2:[
  turn("La tessera della camera non funziona.",[["The key card still doesn't work. Could someone help me?",1,"La reception comprende problema e richiesta."],["The key card didn't work tomorrow.",0,"Il tempo verbale contraddice la situazione presente."],["Someone is a key card.",0,"La frase non identifica il problema."]]),
  turn("Hai perso una coincidenza e arriverai tardi.",[["I've missed my connection, so I'll arrive about twenty minutes late.",1,"Il destinatario riceve causa e nuovo orario."],["I miss the train every twenty minutes.",0,"Descrive un’abitudine, non l’imprevisto attuale."],["The connection arrived me.",0,"Il verbo non esprime ciò che è accaduto."]]),
  turn("Il cameriere porta un piatto diverso.",[["Excuse me, I ordered the soup, not the salad.",1,"Correggi l’ordine con cortesia e precisione."],["This food is impossible.",0,"Esprime insoddisfazione senza identificare l’errore."],["You are wrong food.",0,"La frase è aggressiva e grammaticalmente scorretta."]])],
 B1:[
  turn("Un ordine contiene due articoli, ma ne sono stati addebitati tre.",[["Could you check whether the third item was dispatched separately?",1,"Chiedi una verifica prima di accusare o pretendere un rimborso."],["You stole the price of one item.",0,"L’accusa non è sostenuta dai fatti disponibili."],["Maybe the third item is a price.",0,"Non distingue articolo, addebito e spedizione."],["Everything in the order is wrong.",0,"Generalizza e rende più difficile risolvere il caso."]]),
  turn("Un collega non riesce a finire il lavoro oggi.",[["What is blocking you, and which part should we prioritise?",1,"Individui causa e priorità prima di cambiare il piano."],["I will do all your work.",0,"Elimini responsabilità senza capire il problema."],["Try harder and finish somehow.",0,"Non offre diagnosi né supporto concreto."],["The deadline does not matter.",0,"Ignora un vincolo che potrebbe essere importante."]]),
  turn("Devi dissentire durante una riunione.",[["I see the benefit, but I'm concerned about the implementation time.",1,"Riconosci il punto valido e delimiti il disaccordo."],["No, this is completely wrong.",0,"Rifiuta senza spiegare quale parte non convince."],["I agree, but I disagree with everything.",0,"Le due posizioni dichiarate si contraddicono e non chiariscono il tuo giudizio."],["Your idea cannot work anywhere.",0,"Usa un assoluto non sostenuto da evidenze."]])],
 B2:[
  turn("Il cliente chiede una data certa, ma il corriere non ha confermato.",[["I can't confirm a date yet, but I'll verify the status and update you by four.",1,"Distingui ciò che sai da ciò che verificherai e dai una scadenza."],["It will definitely arrive tomorrow.",0,"Prometti un risultato non confermato."],["The courier is usually reliable, so there is no issue.",0,"Minimizzi il problema senza verificarlo."],["Delivery dates are outside our control.",0,"Scarichi la responsabilità senza proporre un’azione."],["Perhaps it arrives at some point this week.",0,"L’incertezza resta priva di un prossimo passo."]]),
  turn("Il progetto può partire solo con capacità di assistenza sufficiente.",[["We can proceed provided that support capacity is tested before launch.",1,"Trasformi il rischio in una condizione verificabile."],["We can proceed because support will probably cope.",0,"Una probabilità non dimostrata sostituisce la verifica."],["We should launch and discuss capacity later.",0,"Sposti il controllo dopo l’esposizione al rischio."],["Capacity is irrelevant if the product is good.",0,"Confondi qualità del prodotto e capacità operativa."],["Let us reduce the evidence required.",0,"Riduci il controllo invece del rischio."]]),
  turn("Una proposta ha vantaggi, ma la stima dei costi sembra incompleta.",[["Although the operational benefit is clear, the estimate may understate implementation costs.",1,"Concedi il vantaggio e circoscrivi la criticità."],["The proposal is useful, therefore the estimate is wrong.",0,"La conclusione non deriva logicamente dalla premessa."],["Costs are always higher than expected.",0,"Un assoluto sostituisce l’analisi della stima."],["I can see both sides, so no review is needed.",0,"L’equilibrio dichiarato elimina il controllo necessario."],["The estimate feels bad.",0,"Il giudizio non identifica dati o categorie mancanti."]])],
 C1:[
  turn("I dati mostrano un’associazione, ma non provano causalità.",[["The findings warrant attention, although the causal interpretation remains unsubstantiated.",1,"Preservi il valore del dato senza eccedere ciò che dimostra."],["The association clearly proves the proposed mechanism.",0,"Trasformi correlazione in causalità."],["The findings are meaningless because causality is uncertain.",0,"Scarti impropriamente un’associazione informativa."],["Causality is likely, which makes further analysis unnecessary.",0,"Una probabilità non elimina la necessità di verifica."],["No conclusion of any kind can be drawn.",0,"Confondi cautela causale e assenza totale di evidenza."]]),
  turn("Una clausola sembra accettare il principio, ma rinvia l’impegno.",[["The wording acknowledges the principle while stopping short of a binding commitment.",1,"Distingui riconoscimento retorico e obbligo formale."],["The wording constitutes unconditional acceptance.",0,"Ignori il rinvio dell’impegno e trasformi una cautela in accettazione piena."],["The clause rejects the principle outright.",0,"Contraddici il riconoscimento espresso."],["The ambiguity has no practical consequence.",0,"Sottovaluti l’effetto negoziale dell’ambiguità."],["Any acknowledgement is legally binding.",0,"Generalizzi oltre le informazioni disponibili."]]),
  turn("Devi correggere diplomaticamente un’interpretazione troppo netta.",[["That reading is plausible, but it may overlook an important qualification in the final paragraph.",1,"Riconosci la plausibilità e indichi il limite preciso."],["Your interpretation is obviously wrong.",0,"Attacchi la persona senza discutere il testo."],["Every interpretation is equally valid.",0,"Elimini la possibilità di valutare le evidenze."],["The final paragraph proves my view beyond doubt.",0,"Usi un’assolutezza non giustificata."],["We should avoid interpreting the paragraph.",0,"Rinunci all’analisi invece di migliorarla."]])]
};
