import type { Cefr } from "./curriculum";

export type PrecisionQuestion = {
  prompt: string;
  options: string[];
  answer: number;
  explanationIt: string;
};
export function precisionIsCorrect(question:PrecisionQuestion,choice:number){return choice===question.answer}

export const semanticPrecision: Record<Cefr, PrecisionQuestion[]> = {
  A1: [
    { prompt: "Please ___ this picture.", options: ["look at", "see", "watch"], answer: 0, explanationIt: "Look at indica l'azione volontaria di dirigere lo sguardo verso qualcosa di fermo." },
    { prompt: "I can ___ music in the next room.", options: ["hear", "listen to", "sound"], answer: 0, explanationIt: "Hear descrive un suono che arriva alle orecchie; listen to indica invece l'ascolto intenzionale." },
    { prompt: "Can you ___ hello to Anna?", options: ["say", "tell", "speak"], answer: 0, explanationIt: "Say introduce le parole pronunciate: say hello. Tell richiede normalmente una persona o un'informazione." },
    { prompt: "After work, I go ___.", options: ["home", "house", "room"], answer: 0, explanationIt: "Con il movimento verso casa si dice go home, senza to; house indica l'edificio." },
    { prompt: "What time do you start ___?", options: ["work", "job", "office"], answer: 0, explanationIt: "Work è l'attività lavorativa; job è il posto o ruolo specifico." },
    { prompt: "She is ___ a blue jacket.", options: ["wearing", "carrying", "holding"], answer: 0, explanationIt: "Wear si usa per vestiti e accessori indossati sul corpo." },
    { prompt: "Our teacher ___ us English.", options: ["teaches", "studies", "learns"], answer: 0, explanationIt: "Teach significa insegnare a qualcuno; study e learn descrivono l'attività dello studente." },
    { prompt: "That joke is very ___.", options: ["funny", "fun", "happy"], answer: 0, explanationIt: "Funny descrive qualcosa che fa ridere; fun indica un'attività piacevole." },
    { prompt: "Please ___ to me carefully.", options: ["listen", "hear", "sound"], answer: 0, explanationIt: "Listen indica attenzione volontaria e si costruisce con to davanti alla persona o al suono." },
    { prompt: "I ___ my homework after dinner.", options: ["do", "make", "work"], answer: 0, explanationIt: "Do homework è la combinazione fissa; make si usa quando si crea o produce qualcosa." },
    { prompt: "She ___ a photo with her phone.", options: ["takes", "makes", "does"], answer: 0, explanationIt: "In inglese si dice take a photo, non make a photo." },
    { prompt: "Can you ___ English?", options: ["speak", "say", "tell"], answer: 0, explanationIt: "Speak si usa con il nome di una lingua; say introduce parole e tell una persona." },
    { prompt: "I am looking ___ my keys.", options: ["for", "at", "after"], answer: 0, explanationIt: "Look for significa cercare; look at significa guardare e look after prendersi cura." },
    { prompt: "He goes to work ___ bus.", options: ["by", "on", "with"], answer: 0, explanationIt: "Per il mezzo di trasporto in generale si usa by: by bus." },
    { prompt: "I ___ at seven, but I get out of bed at seven fifteen.", options: ["wake up", "get up", "stand up"], answer: 0, explanationIt: "Wake up significa smettere di dormire; get up significa lasciare il letto." },
  ],
  A2: [
    { prompt: "Can I ___ your dictionary for a moment?", options: ["borrow", "lend", "give"], answer: 0, explanationIt: "Borrow significa ricevere temporaneamente; lend significa prestare a un'altra persona." },
    { prompt: "Please ___ me the umbrella from the hall.", options: ["bring", "take", "carry"], answer: 0, explanationIt: "Bring può avere la costruzione bring someone something e indica movimento verso chi parla." },
    { prompt: "Please ___ me to call the dentist.", options: ["remind", "remember", "recall"], answer: 0, explanationIt: "Remind significa aiutare un'altra persona a ricordare; remember riguarda la propria memoria." },
    { prompt: "I ___ the bus, so I arrived late.", options: ["missed", "lost", "left"], answer: 0, explanationIt: "Miss a bus significa non riuscire a prenderlo; lose significa smarrire qualcosa." },
    { prompt: "We ___ at the hotel just before midnight.", options: ["arrived", "reached", "came"], answer: 0, explanationIt: "Arrive richiede at davanti a un luogo preciso; reach non vuole preposizione." },
    { prompt: "Could you ___ me the way to the station?", options: ["tell", "say", "speak"], answer: 0, explanationIt: "Tell si costruisce con la persona: tell me. Say non prende direttamente questo complemento." },
    { prompt: "I need to ___ a decision today.", options: ["make", "do", "take"], answer: 0, explanationIt: "Make a decision è la combinazione normale in inglese." },
    { prompt: "The children had great ___ at the party.", options: ["fun", "funny", "amusing"], answer: 0, explanationIt: "Have fun significa divertirsi; funny e amusing sono aggettivi e non completano questa costruzione." },
    { prompt: "Could you ___ my cat while I am away?", options: ["look after", "look for", "look at"], answer: 0, explanationIt: "Look after significa prendersi cura; look for cercare e look at guardare." },
    { prompt: "My grandfather ___ me how to play chess.", options: ["taught", "learned", "studied"], answer: 0, explanationIt: "Teach someone how to do something significa insegnare; learn descrive chi apprende." },
    { prompt: "She is away on a business ___.", options: ["trip", "travel", "journey"], answer: 0, explanationIt: "Business trip è la collocazione normale; travel è l'attività generale del viaggiare." },
    { prompt: "Let me give you some ___.", options: ["advice", "advise", "advising"], answer: 0, explanationIt: "Advice è il sostantivo non numerabile; advise è il verbo." },
    { prompt: "The room is ___ small, but it is comfortable.", options: ["quite", "quiet", "silently"], answer: 0, explanationIt: "Quite è un avverbio di grado; quiet significa silenzioso." },
    { prompt: "Be careful not to ___ your passport.", options: ["lose", "miss", "fail"], answer: 0, explanationIt: "Lose significa smarrire un oggetto; miss significa non prendere un mezzo o sentire la mancanza." },
    { prompt: "We sat in the ___ of a large tree.", options: ["shade", "shadow", "dark"], answer: 0, explanationIt: "Shade è la zona riparata dal sole; shadow è la sagoma scura proiettata da qualcosa." },
  ],
  B1: [
    { prompt: "The price of fuel continues to ___.", options: ["rise", "raise", "arise", "grow up"], answer: 0, explanationIt: "Rise è intransitivo: il prezzo sale. Raise richiede un oggetto: raise the price." },
    { prompt: "This small car is very ___ to run.", options: ["economical", "economic", "financial", "cheaply"], answer: 0, explanationIt: "Economical significa poco costoso o parsimonioso; economic riguarda l'economia." },
    { prompt: "It would be ___ to check the weather first.", options: ["sensible", "sensitive", "sensory", "sentimental"], answer: 0, explanationIt: "Sensible significa ragionevole; sensitive significa sensibile." },
    { prompt: "The new barrier should ___ accidents.", options: ["prevent", "avoid", "protect", "escape"], answer: 0, explanationIt: "Prevent something significa impedire che accada; avoid significa tenersi lontani da qualcosa." },
    { prompt: "After years of training, she finally ___ in becoming a pilot.", options: ["succeeded", "achieved", "reached", "managed"], answer: 0, explanationIt: "Succeed si costruisce con in + -ing; achieve richiede un oggetto e manage richiede to + verbo." },
    { prompt: "He ___ taking the missing documents.", options: ["denied", "refused", "rejected", "declined"], answer: 0, explanationIt: "Deny + -ing significa negare di aver fatto qualcosa; refuse significa rifiutarsi di agire." },
    { prompt: "This tool was ___ made for left-handed users.", options: ["specially", "especially", "special", "especial"], answer: 0, explanationIt: "Specially indica uno scopo particolare; especially significa soprattutto, mentre special ed especial sono aggettivi." },
    { prompt: "I don't ___ where I left the receipt.", options: ["remember", "remind", "recognise", "repeat"], answer: 0, explanationIt: "Remember significa avere qualcosa nella memoria; remind richiede chi viene aiutato a ricordare." },
    { prompt: "The change may ___ customer confidence.", options: ["affect", "effect", "infect", "reflect"], answer: 0, explanationIt: "Affect è normalmente il verbo che significa influenzare; effect è soprattutto un sostantivo." },
    { prompt: "Over two hundred people ___ the conference.", options: ["attended", "assisted", "participated", "visited to"], answer: 0, explanationIt: "Attend prende direttamente l'evento; participate richiede in e assist non significa partecipare." },
    { prompt: "Guests wore traditional ___ for the ceremony.", options: ["costume", "custom", "customs", "customer"], answer: 0, explanationIt: "Costume indica un abito caratteristico; custom è una tradizione e customs la dogana." },
    { prompt: "Please ___ the document on my desk.", options: ["lay", "lie", "laid", "lain"], answer: 0, explanationIt: "Lay richiede un oggetto: lay the document. Lie significa giacere e non prende oggetto." },
    { prompt: "I am gradually ___ working night shifts.", options: ["getting used to", "used to", "use to", "getting use to"], answer: 0, explanationIt: "Get used to + -ing descrive il processo di abituarsi." },
    { prompt: "The internship gave her an ___ to use French at work.", options: ["opportunity", "occasion", "possibility", "probability"], answer: 0, explanationIt: "An opportunity to do something è un'occasione concreta favorevole." },
    { prompt: "Could we ___ the issue before the meeting ends?", options: ["discuss", "talk", "speak", "tell"], answer: 0, explanationIt: "Discuss prende direttamente l'argomento; talk e speak richiedono about." },
  ],
  B2: [
    { prompt: "The new procedure will ___ that every complaint is recorded.", options: ["ensure", "assure", "insure", "reassure"], answer: 0, explanationIt: "Ensure significa garantire un risultato; assure e reassure si rivolgono normalmente a una persona." },
    { prompt: "Her silence seemed to ___ that she disagreed.", options: ["imply", "infer", "deduce", "conclude"], answer: 0, explanationIt: "Chi comunica implies; chi ascolta o legge infers." },
    { prompt: "The redesigned engine is more fuel-___.", options: ["efficient", "effective", "productive", "sufficient"], answer: 0, explanationIt: "Efficient significa ottenere il risultato con meno sprechi; effective significa capace di produrre l'effetto." },
    { prompt: "The department offers a course in ___ linguistics.", options: ["historical", "historic", "history", "historically"], answer: 0, explanationIt: "Historical linguistics è il nome della disciplina che studia il cambiamento delle lingue nel tempo." },
    { prompt: "The company decided to ___ a more flexible policy.", options: ["adopt", "adapt", "adjust", "convert"], answer: 0, explanationIt: "Adopt significa scegliere e applicare; adapt significa modificare per una nuova situazione." },
    { prompt: "The blue curtains ___ the pale walls perfectly.", options: ["complement", "compliment", "complete", "supplement"], answer: 0, explanationIt: "Complement significa completare armoniosamente; compliment significa fare un complimento." },
    { prompt: "Only authorised staff may ___ the database using a secure password.", options: ["access", "assess", "excess", "possess"], answer: 0, explanationIt: "Access significa entrare in un sistema; assess significa valutare ed excess è un sostantivo o aggettivo." },
    { prompt: "The school ___ addressed the parents.", options: ["principal", "principle", "principled", "principally"], answer: 0, explanationIt: "Principal è il dirigente scolastico; principle è un principio, principled è un aggettivo e principally un avverbio." },
    { prompt: "The collection ___ twelve original manuscripts.", options: ["comprises", "consists", "composes", "is comprised"], answer: 0, explanationIt: "Comprise prende direttamente le parti; consist richiede of e compose ha le parti come soggetto." },
    { prompt: "The medicine had no noticeable ___.", options: ["effect", "affect", "effective", "effectively"], answer: 0, explanationIt: "Effect è il sostantivo; affect è normalmente un verbo, effective un aggettivo ed effectively un avverbio." },
    { prompt: "This year there were ___ complaints than last year.", options: ["fewer", "less", "lower", "smaller"], answer: 0, explanationIt: "Fewer si usa con nomi numerabili plurali; less con quantità non numerabili." },
    { prompt: "His evidence ___ my earlier suspicion.", options: ["confirmed", "conformed", "affirmed", "reassured"], answer: 0, explanationIt: "Confirm significa dimostrare che un'idea precedente era corretta; conform richiede normalmente to." },
    { prompt: "The match was ___ and will not be played at all.", options: ["cancelled", "postponed", "suspended", "delayed"], answer: 0, explanationIt: "Cancelled significa annullato definitivamente; le altre alternative indicano uno spostamento o un'interruzione." },
    { prompt: "Online sales ___ nearly half of our revenue.", options: ["account for", "explain", "justify", "stand by"], answer: 0, explanationIt: "Account for significa costituire una determinata percentuale del totale." },
    { prompt: "Several unexpected difficulties ___ during testing.", options: ["arose", "rose", "raised", "lifted"], answer: 0, explanationIt: "Arise significa emergere o presentarsi; rise indica salire e raise richiede un oggetto." },
  ],
  C1: [
    { prompt: "Having no personal stake, rather than lacking curiosity, the reviewer was ___.", options: ["disinterested", "uninterested", "indifferent", "inattentive", "apathetic"], answer: 0, explanationIt: "Disinterested significa imparziale; le altre alternative indicano mancanza d'interesse o attenzione." },
    { prompt: "The questioning was designed to ___ information without revealing the hypothesis.", options: ["elicit", "illicit", "extract", "solicit", "evoke"], answer: 0, explanationIt: "Elicit significa far emergere una risposta o informazione; illicit significa illegale." },
    { prompt: "The regulator may ___ practices that distort competition.", options: ["proscribe", "prescribe", "propose", "proclaim", "provide"], answer: 0, explanationIt: "Proscribe significa vietare; prescribe significa ordinare o raccomandare." },
    { prompt: "The consultant was asked to ___ the board of the revised valuation.", options: ["apprise", "appraise", "praise", "prise", "comprise"], answer: 0, explanationIt: "Apprise someone of something significa informarlo; appraise significa valutare." },
    { prompt: "The path through the mountains was narrow and ___.", options: ["tortuous", "torturous", "tormented", "torturing", "arduousness"], answer: 0, explanationIt: "Tortuous significa pieno di curve o complesso; torturous significa estremamente doloroso." },
    { prompt: "The machine ran ___ for 72 hours without stopping.", options: ["continuously", "continually", "successively", "recurringly", "intermittently"], answer: 0, explanationIt: "Continuously significa senza interruzione; continually indica ripetizioni e intermittently pause regolari." },
    { prompt: "The witness gave a ___ account, although it was later disproved.", options: ["credible", "creditable", "credulous", "credibility", "incredulous"], answer: 0, explanationIt: "Credible significa plausibile; creditable significa meritevole e credulous descrive chi crede troppo facilmente." },
    { prompt: "The measures may ___ the immediate effects without addressing the cause.", options: ["mitigate", "eradicate", "aggravate", "magnify", "perpetuate"], answer: 0, explanationIt: "Mitigate significa ridurre la gravità; le altre opzioni eliminano, peggiorano o prolungano il problema." },
    { prompt: "She has a strong ___ to any form of unnecessary risk.", options: ["aversion", "averse", "adverse", "adversity", "adversely"], answer: 0, explanationIt: "Aversion è il sostantivo richiesto dopo strong; averse e adverse sono aggettivi." },
    { prompt: "The engineer's clever and original solution was truly ___.", options: ["ingenious", "ingenuous", "intuitive", "innocent", "genuine"], answer: 0, explanationIt: "Ingenious significa ingegnoso e originale; ingenuous significa innocente o privo di malizia." },
    { prompt: "The company continued to ___ the safety regulations openly.", options: ["flout", "flaunt", "display", "brandish", "parade"], answer: 0, explanationIt: "Flout significa violare apertamente una regola; flaunt significa ostentare." },
    { prompt: "The bank agreed to ___ the administration fee.", options: ["waive", "waver", "wave", "waft", "weigh"], answer: 0, explanationIt: "Waive significa rinunciare a un diritto o pagamento; waver significa esitare." },
    { prompt: "The equipment will ___ rapidly in value if it is not maintained.", options: ["depreciate", "deprecate", "deprive", "depress", "deplete"], answer: 0, explanationIt: "Depreciate significa perdere valore; deprecate significa disapprovare o scoraggiare." },
    { prompt: "The regulator warned firms not to become ___ about familiar risks.", options: ["complacent", "complaisant", "compliant", "complicit", "complementary"], answer: 0, explanationIt: "Complacent significa eccessivamente sicuro e poco vigile; complaisant significa desideroso di compiacere." },
    { prompt: "The disease is ___ to this particular region.", options: ["endemic", "epidemic", "pandemic", "systemic", "sporadic"], answer: 0, explanationIt: "Endemic indica una presenza stabilmente limitata a una zona o popolazione." },
  ],
};
