import { useMemo, useState } from "react";
import { shuffled } from "./random";
import type { Cefr } from "./curriculum";
import { getAudioAccent } from "./preferences";
import { realDialogues } from "./realDialogues";

type Lab = "menu" | "errors" | "pairs" | "pronunciation" | "mediation" | "families" | "dialogue" | "shadowing" | "define" | "daily" | "dictation" | "paraphrase" | "reconstruct";
const errorBank = [
  ["I am agree with you.", "I agree with you.", "Agree è un verbo e non richiede am."],
  ["She don't work here.", "She doesn't work here.", "Con she usa doesn't + verbo base."],
  ["I have seen him yesterday.", "I saw him yesterday.", "Yesterday indica un tempo concluso: Past Simple."],
  ["The report must to be revised.", "The report must be revised.", "Dopo un modale usa il verbo base senza to."],
  ["Despite of the delay, we finished.", "Despite the delay, we finished.", "Despite è seguito direttamente dal nome."],
] as const;
const pairs = [["ship", "sheep"], ["live", "leave"], ["three", "tree"], ["think", "sink"], ["bat", "bet"], ["worked", "walked"]] as const;
export const pronunciationDrills: Record<Cefr, { word: string; stress: string; contrast: string; instruction: string; example: string }[]> = {
  A1: [
    { word: "three", stress: "THREE", contrast: "tree", instruction: "Metti la punta della lingua leggermente tra i denti e lascia passare l’aria. Non trasformare th in t.", example: "I need three tickets." },
    { word: "ship", stress: "SHIP", contrast: "sheep", instruction: "Usa una vocale breve e rilassata. Non allungarla come nella parola sheep.", example: "The ship is here." },
    { word: "water", stress: "WA-ter", contrast: "Walter", instruction: "Accenta la prima sillaba e rendi la seconda molto breve.", example: "Could I have some water?" },
    { word: "please", stress: "PLEASE", contrast: "place", instruction: "Mantieni la vocale lunga e termina con il suono sonoro z.", example: "A coffee, please." },
  ],
  A2: [
    { word: "worked", stress: "WORKED", contrast: "walked", instruction: "La terminazione -ed qui suona t, senza creare una sillaba aggiuntiva.", example: "I worked yesterday." },
    { word: "leave", stress: "LEAVE", contrast: "live", instruction: "Allunga la vocale ee; live ha invece una vocale breve.", example: "We leave at six." },
    { word: "comfortable", stress: "COMF-ta-ble", contrast: "comfort table", instruction: "Riduci le sillabe centrali: nel parlato naturale non si scandisce ogni lettera.", example: "This chair is comfortable." },
    { word: "hotel", stress: "ho-TEL", contrast: "HO-tel", instruction: "L’accento principale cade sulla seconda sillaba.", example: "The hotel is nearby." },
  ],
  B1: [
    { word: "development", stress: "de-VEL-op-ment", contrast: "DE-velopment", instruction: "Metti l’accento sulla seconda sillaba e riduci la prima.", example: "The development took a year." },
    { word: "thought", stress: "THOUGHT", contrast: "taught", instruction: "Inizia con la lingua tra i denti; il resto della parola forma una sola sillaba.", example: "I thought about the proposal." },
    { word: "focus", stress: "FO-cus", contrast: "fo-CUS", instruction: "Accenta la prima sillaba e riduci la seconda verso un suono neutro.", example: "Let us focus on the result." },
    { word: "world", stress: "WORLD", contrast: "word", instruction: "Fai sentire la l prima della d senza aggiungere una vocale finale.", example: "It changed the world." },
  ],
  B2: [
    { word: "reliable", stress: "re-LI-a-ble", contrast: "RE-liable", instruction: "L’accento cade sulla seconda sillaba; le sillabe non accentate restano leggere.", example: "We need reliable evidence." },
    { word: "analysis", stress: "a-NA-ly-sis", contrast: "analyse", instruction: "Nel nome analysis l’accento cade sulla seconda sillaba.", example: "The analysis is incomplete." },
    { word: "particularly", stress: "par-TIC-u-lar-ly", contrast: "particular", instruction: "Mantieni chiara la sillaba accentata e riduci quelle circostanti.", example: "This is particularly important." },
    { word: "thorough", stress: "THOR-ough", contrast: "though", instruction: "Apri con th e pronuncia due sillabe; non confonderla con though.", example: "We need a thorough review." },
  ],
  C1: [
    { word: "interpretation", stress: "in-ter-pre-TA-tion", contrast: "interpret", instruction: "Nel nome lungo l’accento principale si sposta sulla sillaba ta.", example: "That interpretation is plausible." },
    { word: "accountability", stress: "a-count-a-BIL-i-ty", contrast: "accountable", instruction: "Sposta l’accento su bil e riduci le sillabe vicine.", example: "Public accountability matters." },
    { word: "ambiguity", stress: "am-bi-GU-i-ty", contrast: "ambiguous", instruction: "Nel nome accentua gu; nell’aggettivo l’accento cambia.", example: "The wording creates ambiguity." },
    { word: "statistically", stress: "sta-TIS-ti-cal-ly", contrast: "statistic", instruction: "Conserva il ritmo mettendo in rilievo tis e riducendo le altre sillabe.", example: "The difference is statistically significant." },
  ],
};
export const pronunciationWordRecognised = (spoken: string, target: string) => spoken.toLowerCase().replace(/[^a-z]/g, "").includes(target.toLowerCase().replace(/[^a-z]/g, ""));
const familyTasks = [
  { prompt: "decide", answer: "decision", options: ["decision", "description", "discussion", "selection"], family: ["decide", "decision", "decisive", "decisively"], note: "Decision è il nome formato dal verbo decide; le altre alternative sono nomi reali, ma appartengono ad altre famiglie." },
  { prompt: "succeed", answer: "successful", options: ["successful", "successive", "sufficient", "supportive"], family: ["succeed", "success", "successful", "successfully"], note: "Successful è l’aggettivo della famiglia di succeed. Successive è simile nella forma, ma significa consecutivo." },
  { prompt: "analysis", answer: "analytical", options: ["analytical", "analogous", "additional", "artificial"], family: ["analyse", "analysis", "analytical", "analytically"], note: "Analytical è l’aggettivo collegato ad analysis; analogous appartiene a una famiglia e a un significato differenti." },
  { prompt: "reliable", answer: "reliability", options: ["reliability", "reluctance", "relevance", "resilience"], family: ["rely", "reliability", "reliable", "reliably"], note: "Reliability è il nome collegato a reliable. Le altre opzioni sono nomi astratti plausibili, ma non della stessa famiglia." },
] as const;
const mediation: Record<Cefr, { it: string; keywords: string[]; model: string }> = {
  A1: { it: "Dì a un collega inglese che la riunione è domani alle dieci.", keywords: ["meeting", "tomorrow", "ten"], model: "The meeting is tomorrow at ten." },
  A2: { it: "Spiega che il treno è in ritardo e arriverai circa venti minuti dopo.", keywords: ["train", "late", "twenty"], model: "My train is late, so I will arrive about twenty minutes later." },
  B1: { it: "Comunica che il documento è quasi pronto, ma servono ancora i dati del cliente.", keywords: ["document", "ready", "client"], model: "The document is almost ready, but we still need the client's data." },
  B2: { it: "Riassumi: la proposta riduce i costi, ma richiede formazione e un periodo di prova.", keywords: ["cost", "training", "trial"], model: "The proposal reduces costs, but it requires training and a trial period." },
  C1: { it: "Spiega con cautela che i risultati sono promettenti, ma non dimostrano ancora un rapporto causale.", keywords: ["promising", "prove", "causal"], model: "The findings are promising, but they do not yet prove a causal relationship." },
};
const shadowing: Record<Cefr, string[]> = {
  A1: ["Could I have a glass of water, please?", "I usually start work at nine.", "Where is the nearest bus stop?"],
  A2: ["I was cooking when the phone rang.", "If it rains, we will stay at home.", "I have already sent the message."],
  B1: ["The meeting was postponed because two colleagues were absent.", "I would appreciate it if you could confirm the booking.", "We have been working on this project since March."],
  B2: ["Although the proposal is promising, several practical issues remain unresolved.", "The delay could have been avoided if the warning had been taken seriously.", "What concerns me most is the lack of reliable evidence."],
  C1: ["The findings should be interpreted cautiously, particularly given the limited sample size.", "Had the stakeholders been consulted earlier, the transition might have been considerably smoother.", "The argument is persuasive insofar as it distinguishes correlation from causation."],
};
const definitions: Record<Cefr, { word: string; keywords: string[]; model: string }[]> = {
  A1: [{ word: "kettle", keywords: ["water", "hot", "boil"], model: "It is a kitchen object used to boil water." }],
  A2: [{ word: "neighbour", keywords: ["person", "live", "near"], model: "A person who lives near you." }],
  B1: [{ word: "deadline", keywords: ["time", "finish", "work"], model: "The latest time by which work must be finished." }],
  B2: [{ word: "compromise", keywords: ["agreement", "both", "accept"], model: "An agreement in which both sides accept less than they originally wanted." }],
  C1: [{ word: "accountability", keywords: ["responsible", "decision", "explain"], model: "The duty to be responsible for decisions and explain their consequences." }],
};
const dictations:Record<Cefr,string>={A1:"The train leaves from platform six at nine fifteen.",A2:"Please call reception if the new key card does not work.",B1:"The agent needs to check whether the headphones were dispatched separately.",B2:"We can limit the launch provided that response times are monitored daily.",C1:"The concession remains subject to approval and does not settle the outstanding liability issue."};
const paraphrases:Record<Cefr,{source:string;instruction:string;signals:string[];model:string}>={
 A1:{source:"I want a coffee.",instruction:"Rendi la richiesta più cortese.",signals:["would","like","please"],model:"I’d like a coffee, please."},
 A2:{source:"The key card does not work. Send someone.",instruction:"Trasforma le due frasi in una richiesta cortese e specifica.",signals:["could","someone","card"],model:"The key card still does not work. Could someone come and take a look?"},
 B1:{source:"You sent only two products. Give me my money back.",instruction:"Scrivi un reclamo fermo ma professionale, distinguendo il fatto dalla soluzione richiesta.",signals:["order","received","refund"],model:"My order confirmation lists three products, but I received only two. Could you please issue a refund for the missing item?"},
 B2:{source:"The plan is good, but it costs too much.",instruction:"Esprimi una concessione e delimita con precisione il problema.",signals:["although","benefit","cost"],model:"Although the plan offers a clear operational benefit, the current estimate may understate the implementation cost."},
 C1:{source:"We can talk, but we are not accepting your offer.",instruction:"Riformula in registro negoziale preservando la posizione formale.",signals:["without prejudice","discuss","offer"],model:"Without prejudice to our current position, we are willing to discuss the revised offer."}
};
const reconstruction:Record<Cefr,{prompt:string;lines:string[];answer:number;explanation:string}>={
 A1:{prompt:"Hai chiesto se il treno va a Oxford. Quale risposta continua logicamente?",lines:["Yes, but it now leaves from platform six.","A return ticket is cheaper yesterday.","The hotel room is upstairs."],answer:0,explanation:"La risposta conferma la destinazione e aggiorna il binario."},
 A2:{prompt:"La nuova tessera non funziona ancora. Qual è il passo successivo concordato?",lines:["Call reception so someone can come upstairs.","Check out before trying the card.","Book another train at reception."],answer:0,explanation:"Il dialogo aveva concordato di chiamare la reception."},
 B1:{prompt:"Tre prodotti sono stati addebitati. Che cosa va verificato prima?",lines:["Whether the missing item was dispatched separately.","Whether the customer knows the price.","Whether store credit has expired.","Whether the parcel had a label."],answer:0,explanation:"La verifica distingue una spedizione separata da un articolo mancante."},
 B2:{prompt:"Il team limita il lancio a una regione. Quale battuta completa il piano?",lines:["Let us monitor response times and define a threshold for pausing.","The reduced scope guarantees that support cannot fail.","We can remove the action owner.","The capacity assumption no longer needs evidence."],answer:0,explanation:"Monitoraggio, soglia e responsabilità rendono il compromesso verificabile."},
 C1:{prompt:"Il buyer considera tre anni soltanto a nuove condizioni. Come va interpretato?",lines:["As a counterproposal rather than an acceptance.","As unconditional acceptance of the original offer.","As withdrawal from all further negotiation.","As a binding settlement of liability.","As confirmation that service levels are already binding."],answer:0,explanation:"Nuove condizioni producono una controproposta, non un’accettazione."}
};

function playWord(word: string, rate = 0.8) {
  const slug = word.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""),
    audio = new Audio(`${import.meta.env.BASE_URL}audio/words/${slug}.wav`),
    fallback = () => {
      const utterance = new SpeechSynthesisUtterance(word);
      utterance.lang = getAudioAccent();
      utterance.rate = rate;
      speechSynthesis.cancel();
      speechSynthesis.speak(utterance);
    };
  audio.playbackRate = rate;
  audio.onerror = fallback;
  void audio.play().catch(fallback);
}

export default function SkillsLab({ level, onComplete, reviewItems = [] }: { level: Cefr; onComplete: (id: string, score: number) => void; reviewItems?: { prompt: string; answer: string }[] }) {
  const [lab, setLab] = useState<Lab>("menu"), [index, setIndex] = useState(0),
    [selected, setSelected] = useState<number | null>(null), [correct, setCorrect] = useState(0),
    [text, setText] = useState(""), [checked, setChecked] = useState(false),
    [pairTarget, setPairTarget] = useState<0 | 1>(0), [pairReady, setPairReady] = useState(false), [dialogueStep, setDialogueStep] = useState(0),
    [spoken, setSpoken] = useState(""), [recording, setRecording] = useState(false);
  const shuffledPairs = useMemo(() => shuffled(pairs), [lab]);
  const dailyQuestions = useMemo(() => {
    const source = reviewItems.length ? reviewItems : errorBank.map((row) => ({ prompt: row[0], answer: row[1] }));
    return shuffled(source).slice(0, 5);
  }, [level, lab, reviewItems]);
  const reset = (next: Lab) => { setLab(next); setIndex(0); setSelected(null); setCorrect(0); setText(""); setChecked(false); setPairReady(false); setDialogueStep(0); setSpoken(""); setRecording(false); };
  const finish = (id: string, total: number, value = correct) => { onComplete(`skills:${level}:${id}`, Math.round((value / total) * 100)); reset("menu"); };
  const recognize = () => {
    const Ctor = (window as typeof window & { SpeechRecognition?: new () => any; webkitSpeechRecognition?: new () => any }).SpeechRecognition ??
      (window as typeof window & { webkitSpeechRecognition?: new () => any }).webkitSpeechRecognition;
    if (!Ctor) { setSpoken("Riconoscimento vocale non disponibile."); return; }
    const recognition = new Ctor(); recognition.lang = getAudioAccent(); recognition.interimResults = false; recognition.continuous = false;
    recognition.onresult = (event: any) => setSpoken(event.results?.[0]?.[0]?.transcript ?? "");
    recognition.onerror = () => { setSpoken("Voce non riconosciuta. Riprova."); setRecording(false); };
    recognition.onend = () => setRecording(false); setRecording(true); setSpoken(""); recognition.start();
  };
  if (lab === "menu") return <section className="skillsHub"><div className="themeHeading"><span><small>LABORATORI PRATICI · {level}</small><h2>Usa l’inglese, non soltanto riconoscerlo</h2></span><b>12 attività</b></div><div className="skillsCards">
    <button onClick={() => reset("errors")}><b>✎</b><strong>Trova l’errore</strong><small>Correggi frasi reali</small></button>
    <button onClick={() => reset("pairs")}><b>◉</b><strong>Minimal pairs</strong><small>Ascolta suoni simili</small></button>
    <button onClick={() => reset("pronunciation")}><b>声</b><strong>Pronuncia guidata</strong><small>Suono, accento e nuovo tentativo</small></button>
    <button onClick={() => reset("mediation")}><b>IT→EN</b><strong>Mediazione</strong><small>Trasmetti il significato</small></button>
    <button onClick={() => reset("families")}><b>ABC</b><strong>Famiglie di parole</strong><small>Verbo, nome, aggettivo</small></button>
    <button onClick={() => reset("dialogue")}><b>↪</b><strong>Dialogo a bivi</strong><small>Scegli tono e risposta</small></button>
    <button onClick={() => reset("shadowing")}><b>◖</b><strong>Shadowing</strong><small>Ascolta e ripeti subito</small></button>
    <button onClick={() => reset("define")}><b>?</b><strong>Definisci in inglese</strong><small>Spiega senza tradurre</small></button>
    <button onClick={() => reset("daily")}><b>5</b><strong>Sfida quotidiana</strong><small>Priorità ai tuoi errori</small></button>
    <button onClick={() => reset("dictation")}><b>耳</b><strong>Dettato mirato</strong><small>Ascolta e trascrivi</small></button>
    <button onClick={() => reset("paraphrase")}><b>≈</b><strong>Parafrasi</strong><small>Cambia tono e struttura</small></button>
    <button onClick={() => reset("reconstruct")}><b>↕</b><strong>Ricostruisci il dialogo</strong><small>Scegli il seguito logico</small></button>
  </div></section>;
  if (lab === "errors") { const row = errorBank[index]; return <section className="skillSession"><button className="showSolution" onClick={() => reset("menu")}>← Laboratori</button><span className="eyebrow">TROVA L’ERRORE · {index + 1}/{errorBank.length}</span><h1 lang="en">{row[0]}</h1><p>Quale versione corregge la frase?</p><div className="answers">{[row[1], row[0]].sort((a,b)=>index%2?a.localeCompare(b):b.localeCompare(a)).map((option, i) => <button key={option} disabled={selected !== null} className={selected===null?"":option===row[1]?"right":i===selected?"wrong":"dim"} onClick={()=>{setSelected(i);if(option===row[1])setCorrect(v=>v+1)}}><b>{String.fromCharCode(65+i)}</b><span>{option}</span></button>)}</div>{selected!==null&&<><div className="feedback good"><strong>Regola</strong><p>{row[2]}</p></div><button className="continue" onClick={()=>index+1<errorBank.length?(setIndex(v=>v+1),setSelected(null)):finish("errors",errorBank.length)}>{index+1<errorBank.length?"Prossima frase":"Termina"}<b>→</b></button></>}</section> }
  if (lab === "pairs") { const pair=shuffledPairs[index]; const listen=()=>{if(!pairReady){const target=(Math.random()>.5?1:0) as 0|1;setPairTarget(target);setPairReady(true);playWord(pair[target]);return}playWord(pair[pairTarget])}; return <section className="skillSession"><button className="showSolution" onClick={()=>reset("menu")}>← Laboratori</button><span className="eyebrow">MINIMAL PAIRS · {index+1}/{shuffledPairs.length}</span><h1>Quale parola senti?</h1><button className="pairListen" onClick={listen}>{pairReady?"↻ Riascolta la stessa parola":"▶ Ascolta una parola"}</button><div className="pairChoices">{pair.map((word,i)=><button key={word} disabled={!pairReady||selected!==null} className={selected===null?"":i===pairTarget?"right":i===selected?"wrong":"dim"} onClick={()=>{setSelected(i);if(i===pairTarget)setCorrect(v=>v+1);playWord(word)}}>{word}</button>)}</div>{selected!==null&&<button className="continue" onClick={()=>index+1<shuffledPairs.length?(setIndex(v=>v+1),setSelected(null),setPairReady(false)):finish("pairs",shuffledPairs.length)}>{index+1<shuffledPairs.length?"Prossima coppia":"Termina"}<b>→</b></button>}</section> }
  if (lab === "pronunciation") { const drill=pronunciationDrills[level][index], recognised=spoken.toLowerCase().replace(/[^a-z]/g,"").includes(drill.word.toLowerCase().replace(/[^a-z]/g,"")); return <section className="skillSession pronunciationCoach"><button className="showSolution" onClick={()=>reset("menu")}>← Laboratori</button><span className="eyebrow">PRONUNCIA GUIDATA · {index+1}/{pronunciationDrills[level].length}</span><h1 lang="en">{drill.word}</h1><strong className="stressPattern" lang="en">{drill.stress}</strong><p>{drill.instruction}</p><div className="pronunciationModels"><button onClick={()=>playWord(drill.word,0.65)}>▶ Lenta</button><button onClick={()=>playWord(drill.word,0.95)}>▶ Naturale</button><button onClick={()=>playWord(drill.contrast,0.8)}>Confronta: <b lang="en">{drill.contrast}</b></button></div><blockquote lang="en">{drill.example}</blockquote><button className={recording?"recording continue":"continue"} disabled={recording} onClick={recognize}>{recording?"● Registrazione in corso…":"Pronuncia la parola"}</button>{spoken&&<div className={`feedback ${recognised?"good":"bad"}`}><strong>{recognised?"Parola riconosciuta":"Riprova con il movimento indicato"}</strong><p>Il browser ha trascritto: <b lang="en">{spoken}</b></p><small>Questo riscontro verifica la parola riconosciuta, non misura scientificamente i singoli fonemi.</small></div>}{spoken&&<div className="pronunciationNext"><button onClick={()=>{setSpoken("");recognize()}}>Riprova subito</button><button onClick={()=>{const gained=recognised?1:0;if(index+1<pronunciationDrills[level].length){setCorrect(v=>v+gained);setIndex(v=>v+1);setSpoken("")}else finish("pronunciation",pronunciationDrills[level].length,correct+gained)}}>{index+1<pronunciationDrills[level].length?"Prossima parola":"Termina"}</button></div>}</section> }
  if (lab === "mediation") { const task=mediation[level], hits=task.keywords.filter(word=>text.toLowerCase().includes(word)).length; return <section className="skillSession"><button className="showSolution" onClick={()=>reset("menu")}>← Laboratori</button><span className="eyebrow">SFIDA DI MEDIAZIONE · {level}</span><h1>Comunica l’informazione essenziale in inglese</h1><blockquote>{task.it}</blockquote><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Scrivi con parole tue in inglese…" />{!checked?<button className="continue" disabled={text.trim().split(/\s+/).length<4} onClick={()=>setChecked(true)}>Controlla il messaggio<b>→</b></button>:<><div className={`feedback ${hits>=2?"good":"bad"}`}><strong>{hits}/{task.keywords.length} idee chiave riconosciute</strong><p>Modello possibile: <b lang="en">{task.model}</b></p></div><button className="continue" onClick={()=>finish("mediation",task.keywords.length,hits)}>Concludi<b>→</b></button></>}</section> }
  if (lab === "families") { const task=familyTasks[index], options=[...task.options].sort((a,b)=>(a.length+index)%5-(b.length+index)%5); return <section className="skillSession"><button className="showSolution" onClick={()=>reset("menu")}>← Laboratori</button><span className="eyebrow">FAMIGLIE DI PAROLE · {index+1}/{familyTasks.length}</span><h1>Quale parola appartiene alla stessa famiglia di <em>{task.prompt}</em>?</h1><div className="answers">{options.map((option,i)=><button key={option} disabled={selected!==null} className={selected===null?"":option===task.answer?"right":i===selected?"wrong":"dim"} onClick={()=>{setSelected(i);if(option===task.answer)setCorrect(v=>v+1)}}><b>{String.fromCharCode(65+i)}</b><span>{option}</span></button>)}</div>{selected!==null&&<><div className="feedback good"><strong>Confronto linguistico</strong><p>{task.note}</p></div><p className="familyLine">{task.family.join(" · ")}</p><button className="continue" onClick={()=>index+1<familyTasks.length?(setIndex(v=>v+1),setSelected(null)):finish("families",familyTasks.length)}>{index+1<familyTasks.length?"Prossima famiglia":"Termina"}<b>→</b></button></>}</section> }
  if (lab === "shadowing") { const target=shadowing[level][index], expected=target.toLowerCase().replace(/[^a-z' ]/g," ").split(/\s+/).filter(Boolean), heard=spoken.toLowerCase().replace(/[^a-z' ]/g," ").split(/\s+/).filter(Boolean), hits=expected.filter((word,position)=>heard[position]===word).length, score=Math.round((hits/expected.length)*100); return <section className="skillSession"><button className="showSolution" onClick={()=>reset("menu")}>← Laboratori</button><span className="eyebrow">SHADOWING · {index+1}/{shadowing[level].length}</span><h1>Ascolta e ripeti subito</h1><blockquote lang="en">{target}</blockquote><button className="pairListen" onClick={()=>playWord(target)}>▶ Ascolta il modello</button><button className={recording?"recording continue":"continue"} disabled={recording} onClick={recognize}>{recording?"● Sto ascoltando…":"Ripeti adesso"}</button>{spoken&&<div className="feedback good"><strong>{score}% di parole e ordine riconosciuti</strong><p lang="en">{spoken}</p><small>Il punteggio non valuta i singoli fonemi: usa anche il tuo riascolto nella lezione.</small></div>}{spoken&&<button className="continue" onClick={()=>{const gained=score>=75?1:0; if(index+1<shadowing[level].length){setCorrect(v=>v+gained);setIndex(v=>v+1);setSpoken("")}else finish("shadowing",shadowing[level].length,correct+gained)}}>{index+1<shadowing[level].length?"Prossima frase":"Termina"}<b>→</b></button>}</section> }
  if (lab === "define") { const task=definitions[level][0], hits=task.keywords.filter(word=>text.toLowerCase().includes(word)).length; return <section className="skillSession"><button className="showSolution" onClick={()=>reset("menu")}>← Laboratori</button><span className="eyebrow">DEFINISCI SENZA TRADURRE · {level}</span><h1>Spiega <em lang="en">{task.word}</em> usando soltanto l’inglese</h1><textarea lang="en" value={text} onChange={event=>{setText(event.target.value);setChecked(false)}} placeholder="Descrivi in inglese la persona, l’oggetto o l’idea…" />{!checked?<button className="continue" disabled={text.trim().split(/\s+/).length<4} onClick={()=>setChecked(true)}>Controlla la definizione<b>→</b></button>:<><div className={`feedback ${hits>=2?"good":"bad"}`}><strong>{hits}/{task.keywords.length} idee utili riconosciute</strong><p>Un modello possibile: <b lang="en">{task.model}</b></p></div><button className="continue" onClick={()=>finish("define",task.keywords.length,hits)}>Concludi<b>→</b></button></>}</section> }
  if (lab === "dictation") { const target=dictations[level], expected=target.toLowerCase().replace(/[^a-z0-9' ]/g,"").split(/\s+/), received=text.toLowerCase().replace(/[^a-z0-9' ]/g,"").split(/\s+/), hits=expected.filter((word,i)=>received[i]===word).length, score=Math.round(hits/expected.length*100); return <section className="skillSession"><button className="showSolution" onClick={()=>reset("menu")}>← Laboratori</button><span className="eyebrow">DETTATO MIRATO · {level}</span><h1>Ascolta e scrivi la frase completa</h1><button className="pairListen" onClick={()=>playWord(target)}>▶ Ascolta</button><textarea lang="en" value={text} onChange={e=>{setText(e.target.value);setChecked(false)}} placeholder="Scrivi ciò che senti…" />{!checked?<button className="continue" disabled={!text.trim()} onClick={()=>setChecked(true)}>Confronta la trascrizione<b>→</b></button>:<><div className={`feedback ${score>=80?"good":"bad"}`}><strong>{score}% di parole nella posizione corretta</strong><p lang="en">{target}</p><small>Maiuscole e punteggiatura non riducono il punteggio.</small></div><button className="continue" onClick={()=>finish("dictation",100,score)}>Concludi<b>→</b></button></>}</section> }
  if (lab === "paraphrase") { const task=paraphrases[level], value=text.toLowerCase(), hits=task.signals.filter(signal=>value.includes(signal)).length; return <section className="skillSession"><button className="showSolution" onClick={()=>reset("menu")}>← Laboratori</button><span className="eyebrow">PARAFRASI GUIDATA · {level}</span><h1 lang="en">{task.source}</h1><p>{task.instruction}</p><textarea lang="en" value={text} onChange={e=>{setText(e.target.value);setChecked(false)}} placeholder="Riscrivi con parole tue…" />{!checked?<button className="continue" disabled={text.trim().split(/\s+/).length<4} onClick={()=>setChecked(true)}>Confronta la scelta<b>→</b></button>:<><div className={`feedback ${hits>=2?"good":"bad"}`}><strong>{hits}/{task.signals.length} segnali comunicativi riconosciuti</strong><p>Un modello possibile: <b lang="en">{task.model}</b></p><small>Il modello non è l’unica risposta possibile: confronta tono, precisione e completezza.</small></div><button className="continue" onClick={()=>finish("paraphrase",task.signals.length,hits)}>Concludi<b>→</b></button></>}</section> }
  if (lab === "reconstruct") { const task=reconstruction[level], lines=[...task.lines].sort((a,b)=>(a.length+level.length)%7-(b.length+level.length)%7); return <section className="skillSession"><button className="showSolution" onClick={()=>reset("menu")}>← Laboratori</button><span className="eyebrow">COERENZA DEL DIALOGO · {level}</span><h1>{task.prompt}</h1><div className="dialogueChoices">{lines.map((line,i)=>{const original=task.lines.indexOf(line);return <button key={line} disabled={selected!==null} className={selected===null?"":original===task.answer?"right":i===selected?"wrong":"dim"} onClick={()=>{setSelected(i);if(original===task.answer)setCorrect(1)}}><strong lang="en">{line}</strong>{selected!==null&&<small>{original===task.answer?task.explanation:"È grammaticalmente possibile, ma non continua correttamente le informazioni stabilite."}</small>}</button>})}</div>{selected!==null&&<button className="continue" onClick={()=>finish("reconstruct",1)}>Concludi<b>→</b></button>}</section> }
  if (lab === "daily") { const task=dailyQuestions[index]; if(!task) return <section className="skillSession"><button className="continue" onClick={()=>reset("menu")}>Torna ai laboratori</button></section>; return <section className="skillSession"><button className="showSolution" onClick={()=>reset("menu")}>← Laboratori</button><span className="eyebrow">RICHIAMO ATTIVO · {index+1}/{dailyQuestions.length}</span><h1>{task.prompt}</h1><p>Formula mentalmente o ad alta voce la risposta prima di scoprirla.</p>{!checked?<button className="continue" onClick={()=>setChecked(true)}>Mostra la risposta<b>→</b></button>:<><div className="feedback good"><strong>Risposta da confrontare</strong><p lang="en">{task.answer}</p></div><div className="dialogueChoices"><button onClick={()=>{setCorrect(v=>v+1);setSelected(1)}}><strong>La ricordavo correttamente</strong><small>Il punto entrerà nel ripasso dilazionato.</small></button><button onClick={()=>setSelected(0)}><strong>Devo rinforzarla</strong><small>La risposta tornerà più presto.</small></button></div>{selected!==null&&<button className="continue" onClick={()=>index+1<dailyQuestions.length?(setIndex(v=>v+1),setSelected(null),setChecked(false)):finish("daily",dailyQuestions.length,correct+(selected===1?1:0))}>{index+1<dailyQuestions.length?"Prossimo richiamo":"Termina"}<b>→</b></button>}</>}</section> }
  const dialogue = realDialogues[level] ?? [
    { prompt:"Your colleague says: ‘I can’t finish this today.’", options:[["What is blocking you, and how can I help?",1,"Individua l’ostacolo e offre aiuto senza promettere al posto dell’altro."],["I can finish everything for you.",0,"Offre una soluzione, ma elimina responsabilità e vincoli senza prima capirli."],["Can you try to finish it somehow?",0,"Riconosce il problema, ma non cerca la causa né concorda una priorità."],["We will simply move the deadline.",0,"Decide una modifica prima di verificarne impatto e autorizzazione."]] },
    { prompt:"A customer reports that an urgent delivery is late.", options:[["I understand why the delay is a concern. Let me check the confirmed status and the available options.",1,"Riconosce l’impatto, verifica i fatti e apre a soluzioni concrete."],["I understand the concern, but delays sometimes happen.",0,"Riconosce il disagio ma lo minimizza e non propone un’azione."],["The tracking page should probably update soon.",0,"Fornisce una supposizione senza verificare lo stato reale."],["I can assure you it will arrive today.",0,"Promette un risultato non ancora verificato."]] },
    { prompt:"You see an advantage in a proposal but disagree with its current cost estimate.", options:[["I see the operational advantage; however, the current estimate may understate the implementation cost.",1,"Concede il punto valido e delimita con precisione il disaccordo."],["I agree with the advantage, although the proposal is too expensive.",0,"È comprensibile, ma too expensive è più assoluto e meno analitico."],["The estimate is wrong, despite the proposal being useful.",0,"Formula una conclusione netta senza indicare su quali costi si basa."],["I can see both sides, so either option is acceptable.",0,"Evita il disaccordo invece di affrontare il problema della stima."]] },
  ], turn=dialogue[dialogueStep]; return <section className="skillSession"><button className="showSolution" onClick={()=>reset("menu")}>← Laboratori</button><span className="eyebrow">DIALOGO A BIVI · {dialogueStep+1}/{dialogue.length}</span><h1>{turn.prompt}</h1><div className="dialogueChoices">{turn.options.map(([option,ok,note],i)=><button key={String(option)} disabled={selected!==null} className={selected===null?"":ok?"right":i===selected?"wrong":"dim"} onClick={()=>{setSelected(i);if(ok)setCorrect(v=>v+1)}}><strong>{option}</strong>{selected!==null&&<small>{note}</small>}</button>)}</div>{selected!==null&&<button className="continue" onClick={()=>dialogueStep+1<dialogue.length?(setDialogueStep(v=>v+1),setSelected(null)):finish("dialogue",dialogue.length)}>{dialogueStep+1<dialogue.length?"Continua il dialogo":"Termina"}<b>→</b></button>}</section>;
}
