import type { Cefr } from "./curriculum";

export type StoryEpisode = {
  id: string;
  level: Cefr;
  number: number;
  title: string;
  setting: string;
  text: string;
  question: string;
  choices: string[];
  answer: number;
  explanation: string;
  writingPrompt: string;
  model: string;
};

const episode = (
  level: Cefr,
  number: number,
  title: string,
  setting: string,
  text: string,
  question: string,
  choices: string[],
  answer: number,
  explanation: string,
  writingPrompt: string,
  model: string,
): StoryEpisode => ({ id: `story-${level.toLowerCase()}-${number}`, level, number, title, setting, text, question, choices, answer, explanation, writingPrompt, model });

export const storyEpisodes: StoryEpisode[] = [
  episode("A1", 1, "Il nuovo vicino", "Lunedì mattina", "Maya meets Tom in the hall. ‘Hi, I’m Maya. I’m in flat twelve.’ Tom smiles. ‘Nice to meet you. I’m in flat ten.’", "Where does Maya live?", ["In flat ten", "In flat twelve", "At a hotel"], 1, "Maya dice direttamente: I’m in flat twelve.", "Presentati a Tom con nome e città.", "Hi Tom, I’m Elena. I’m from Rome. Nice to meet you."),
  episode("A1", 2, "Una colazione veloce", "Martedì mattina", "Maya is late. At the café she says, ‘A small coffee and a cheese sandwich, please.’ The server asks, ‘For here or to go?’ Maya answers, ‘To go, please.’", "What does Maya take away?", ["A coffee and a sandwich", "Two coffees", "A salad and water"], 0, "Ordina un caffè e un panino e sceglie to go.", "Ordina una bevanda e qualcosa da mangiare.", "I’d like a tea and a ham sandwich, please. To go."),
  episode("A1", 3, "La strada giusta", "Martedì pomeriggio", "Maya cannot find the library. Tom says, ‘Go straight, then turn left at the bank. The library is next to the pharmacy.’", "Where is the library?", ["Behind the bank", "Next to the pharmacy", "Inside the station"], 1, "Next to significa accanto a.", "Spiega un percorso semplice usando go straight e turn.", "Go straight and turn right at the café. The station is on your left."),
  episode("A2", 1, "Il fine settimana", "Venerdì sera", "Maya and Tom are planning a weekend away. They have found a cheap train, but the earliest one leaves at six. Maya would rather travel later, even if the ticket costs more.", "What matters more to Maya?", ["Leaving later", "Buying the cheapest ticket", "Travelling by bus"], 0, "Would rather travel later mostra la sua preferenza.", "Proponi un viaggio e indica quando preferisci partire.", "Why don’t we visit Bristol? I’d rather leave after breakfast."),
  episode("A2", 2, "Cambio di programma", "Sabato mattina", "Their train has been delayed by ninety minutes. Tom has already called the hotel, so the room is still available. Maya buys some food while they wait.", "Why is the hotel room still available?", ["They arrived early", "Tom called the hotel", "Maya paid again"], 1, "Tom has already called: ha già avvisato l’hotel.", "Spiega un ritardo e una soluzione.", "Our train has been delayed, so we called the hotel and changed the arrival time."),
  episode("A2", 3, "Un piccolo imprevisto", "Sabato sera", "At the restaurant, Maya receives the wrong dish. She politely explains that she ordered the vegetable soup, not the chicken. The waiter apologises and replaces it quickly.", "How is the problem solved?", ["Maya leaves", "The waiter replaces the dish", "Tom eats both dishes"], 1, "Il cameriere si scusa e sostituisce il piatto.", "Fai un reclamo gentile al ristorante.", "Excuse me, I ordered the vegetable soup, but this is chicken. Could you change it, please?"),
  episode("B1", 1, "Una nuova proposta", "Lunedì, riunione", "Maya presents an idea for reducing packaging waste. Although the initial cost is higher, the new material can be reused and may save money over time. Her manager asks for clearer figures.", "Why is the manager not ready to approve the idea?", ["The material cannot be reused", "The financial evidence is not clear enough", "Maya missed the meeting", "The long-term saving is already guaranteed"], 1, "Chiede clearer figures: servono dati economici più precisi.", "Riassumi un vantaggio e un limite della proposta.", "The material is more expensive at first, but it can reduce waste and save money in the long term."),
  episode("B1", 2, "Il dato mancante", "Martedì, ufficio", "Tom discovers that one supplier has not sent its monthly report. Without those figures, Maya cannot compare the two materials fairly. They decide to put off the presentation until Thursday.", "Why is the presentation postponed?", ["A supplier’s data is missing", "The manager requested a different comparison", "The material failed its first test", "The supplier changed the meeting date"], 0, "Without those figures non possono fare un confronto corretto.", "Scrivi un breve aggiornamento sul ritardo.", "We have put off the presentation until Thursday because we are still waiting for the supplier’s report."),
  episode("B1", 3, "Una decisione condivisa", "Giovedì, presentazione", "The complete figures show that the reusable material becomes cheaper after eight months. The team agrees to test it on one product before making a final decision.", "What compromise does the team reach?", ["They reject the material until prices fall", "They change every product after eight months", "They run a limited trial first", "They approve it but delay every test"], 2, "Testarlo su un solo prodotto è una prova limitata prima della decisione finale.", "Esprimi accordo con una condizione.", "I agree that we should test it, provided that we review the results after three months."),
  episode("B2", 1, "La trattativa", "Primo incontro", "The supplier claims the new packaging will reduce returns. Maya points out that the evidence comes from a relatively small sample and asks whether an independent laboratory has verified the results.", "What is Maya’s main concern?", ["The evidence is relevant but may not be sufficiently robust", "The evidence is robust but no longer commercially relevant", "The sample is large but the laboratory is too expensive", "The design was verified independently but not tested internally"], 0, "Mette in dubbio solidità e indipendenza delle prove, non il design.", "Formula una richiesta professionale di chiarimento.", "Could you clarify how the sample was selected and whether the results were independently verified?"),
  episode("B2", 2, "Condizioni nascoste", "Secondo incontro", "The price appears competitive; however, the contract requires a three-year commitment and allows annual increases. Had the team noticed the clause earlier, it would have negotiated different terms.", "Why is the apparent price advantage uncertain?", ["Future increases may offset the attractive initial price", "The initial price is fixed but the commitment is too short", "Annual reductions depend on a longer commitment", "The price is competitive only because delivery is excluded"], 0, "Durata e aumenti annuali possono annullare il vantaggio iniziale.", "Spiega un rischio contrattuale e proponi una modifica.", "The initial price is attractive, but the annual increase creates uncertainty. We suggest a fixed price for two years."),
  episode("B2", 3, "L’accordo sostenibile", "Decisione finale", "Both sides eventually accept a one-year pilot with measurable targets. The supplier will lower the price if return rates do not improve, while Maya’s company will share anonymised performance data.", "What makes the agreement balanced?", ["The buyer accepts all financial risk in exchange for data", "Both sides accept duties linked to measurable results", "The supplier guarantees success without changing the price", "Both sides postpone their obligations until after the pilot"], 1, "Obblighi e rischi sono distribuiti e legati a risultati misurabili.", "Riassumi l’accordo in due frasi formali.", "The parties agreed to a one-year pilot governed by measurable targets. Pricing will be adjusted if the expected reduction in returns is not achieved."),
  episode("C1", 1, "Un consenso fragile", "Tavola rotonda", "The chair’s opening remarks were ostensibly conciliatory, yet her insistence on immediate implementation left little room for genuine negotiation. Several participants therefore questioned whether the consultation was substantive or merely procedural.", "What tension shapes the discussion?", ["Inclusive language contrasts with limited room to influence the outcome", "The chair supports negotiation but participants demand immediate implementation", "The consultation is substantive despite an unnecessarily formal procedure", "The timetable is flexible although the chair’s language sounds inflexible", "Participants accept the outcome but question how it was communicated"], 0, "Il tono conciliante contrasta con condizioni che riducono il negoziato reale.", "Valuta con cautela la credibilità della consultazione.", "Although the language appears inclusive, the predetermined timetable may undermine the impression that participants can influence the outcome."),
  episode("C1", 2, "Prove e interpretazioni", "Analisi dei dati", "A decline in complaints coincided with the pilot scheme, but it would be premature to infer causation. Reporting procedures changed during the same period, potentially suppressing the number of recorded cases without improving the underlying service.", "Why is the causal claim weak?", ["The decline is too small to be relevant even if the procedure remained stable", "A concurrent reporting change provides a plausible alternative explanation", "The pilot probably caused the decline but the timetable is unclear", "The reporting change confirms that the underlying service improved", "The number of complaints is reliable although the cause remains unknown"], 1, "Il cambiamento nella segnalazione è una spiegazione alternativa plausibile.", "Distingui correlazione e causalità con registro accademico.", "The observed association is encouraging, but it does not establish causality, since the reporting procedure changed concurrently."),
  episode("C1", 3, "Una raccomandazione prudente", "Documento conclusivo", "Rather than endorsing immediate expansion, Maya recommends a second trial with transparent reporting and a comparison group. This would not eliminate every source of uncertainty, but it would make future conclusions considerably more defensible.", "What is the purpose of Maya’s recommendation?", ["To postpone expansion until every possible uncertainty has disappeared", "To make subsequent conclusions methodologically more defensible", "To confirm the existing conclusion through a larger but otherwise identical trial", "To replace transparent reporting with a more representative sample", "To demonstrate that a comparison group eliminates all uncertainty"], 1, "Propone un disegno migliore per rendere le conclusioni più solide.", "Scrivi una raccomandazione finale equilibrata.", "A further trial is warranted, provided that reporting remains transparent and outcomes are compared with an appropriate control group."),
];
