import type {Cefr} from "./curriculum";
export type VisualItem={en:string;it:string;verb:string;clue?:string};
export type VisualSet={id:string;title:string;image:string;items:VisualItem[];audioMode?:"file"|"browser";levels?:Cefr[]};

export const kitchenVisualSets:VisualSet[]=[
 {id:"basic",levels:["A1"],title:"Utensili essenziali",image:"images/kitchen-utensils-grid.png",items:[
  {en:"wooden spoon",it:"cucchiaio di legno",verb:"stir · mescolare"},{en:"ladle",it:"mestolo",verb:"serve · servire"},{en:"whisk",it:"frusta",verb:"whisk / beat · sbattere"},{en:"spatula",it:"spatola",verb:"flip · girare"},{en:"peeler",it:"pelapatate",verb:"peel · sbucciare"},{en:"grater",it:"grattugia",verb:"grate · grattugiare"},{en:"funnel",it:"imbuto",verb:"pour · versare"},{en:"rolling pin",it:"mattarello",verb:"roll out · stendere"},{en:"chopping board",it:"tagliere",verb:"chop · tritare"}
 ]},
 {id:"cookware",levels:["A1","A2"],title:"Pentole, lame e contenitori",image:"images/kitchen-utensils-grid-2.png",items:[
  {en:"chef's knife",it:"coltello da chef",verb:"slice · affettare"},{en:"paring knife",it:"spelucchino",verb:"peel · sbucciare"},{en:"saucepan",it:"casseruola",verb:"simmer · cuocere lentamente"},{en:"frying pan",it:"padella",verb:"fry · friggere"},{en:"stock pot",it:"pentola alta",verb:"boil · bollire"},{en:"colander",it:"scolapasta",verb:"drain · scolare"},{en:"sieve",it:"setaccio",verb:"sift · setacciare"},{en:"mixing bowl",it:"ciotola da impasto",verb:"mix · mescolare"},{en:"measuring jug",it:"caraffa graduata",verb:"measure · misurare"}
 ]},
 {id:"baking",levels:["A2","B1"],title:"Pasticceria e forno",image:"images/kitchen-utensils-grid-3.png",items:[
  {en:"baking tray",it:"teglia da forno",verb:"bake · cuocere al forno"},{en:"cake tin",it:"stampo per torta",verb:"line · foderare"},{en:"muffin tin",it:"stampo per muffin",verb:"fill · riempire"},{en:"pastry brush",it:"pennello da cucina",verb:"brush · spennellare"},{en:"piping bag",it:"sac à poche",verb:"pipe · decorare"},{en:"cookie cutter",it:"tagliabiscotti",verb:"cut out · ritagliare"},{en:"kitchen scales",it:"bilancia da cucina",verb:"weigh · pesare"},{en:"measuring spoons",it:"cucchiai dosatori",verb:"measure · dosare"},{en:"oven mitt",it:"guanto da forno",verb:"protect · proteggere"}
 ]},
 {id:"gadgets",levels:["B1","B2"],title:"Piccoli strumenti",image:"images/kitchen-utensils-grid-4.png",items:[
  {en:"garlic press",it:"spremiaglio",verb:"crush · schiacciare"},{en:"can opener",it:"apriscatole",verb:"open · aprire"},{en:"bottle opener",it:"apribottiglie",verb:"open · stappare"},{en:"corkscrew",it:"cavatappi",verb:"uncork · stappare"},{en:"kitchen scissors",it:"forbici da cucina",verb:"snip · tagliare"},{en:"kitchen tongs",it:"pinze da cucina",verb:"grip · afferrare"},{en:"potato masher",it:"schiacciapatate",verb:"mash · schiacciare"},{en:"mortar and pestle",it:"mortaio e pestello",verb:"grind · pestare"},{en:"citrus juicer",it:"spremiagrumi",verb:"squeeze · spremere"}
 ]},
 {id:"serving",levels:["B2","C1"],title:"Servire e conservare",image:"images/kitchen-utensils-grid-5.png",items:[
  {en:"slotted spoon",it:"cucchiaio forato",verb:"lift · sollevare"},{en:"skimmer",it:"schiumarola",verb:"skim · schiumare"},{en:"carving fork",it:"forchettone",verb:"hold · tenere fermo"},{en:"serving tray",it:"vassoio",verb:"serve · servire"},{en:"salad bowl",it:"insalatiera",verb:"toss · condire e mescolare"},{en:"pepper mill",it:"macinapepe",verb:"grind · macinare"},{en:"food container",it:"contenitore per alimenti",verb:"store · conservare"},{en:"ice cube tray",it:"vaschetta del ghiaccio",verb:"freeze · congelare"},{en:"thermos flask",it:"thermos",verb:"keep warm · tenere caldo"}
 ]},
 {id:"appliances",levels:["B1","B2","C1"],title:"Elettrodomestici e accessori",image:"images/kitchen-utensils-grid-6.png",items:[
  {en:"kitchen timer",it:"timer da cucina",verb:"time · cronometrare"},{en:"cooking thermometer",it:"termometro da cucina",verb:"check · controllare"},{en:"blender",it:"frullatore",verb:"blend · frullare"},{en:"hand mixer",it:"sbattitore elettrico",verb:"beat · sbattere"},{en:"food processor",it:"robot da cucina",verb:"process · lavorare"},{en:"electric kettle",it:"bollitore elettrico",verb:"boil · bollire"},{en:"toaster",it:"tostapane",verb:"toast · tostare"},{en:"microwave oven",it:"forno a microonde",verb:"reheat · riscaldare"},{en:"kitchen apron",it:"grembiule da cucina",verb:"wear · indossare"}
 ]}
];
const advancedKitchenClues:Record<string,string>={
 "baking tray":"a flat metal sheet used to bake food in the oven","cake tin":"a shaped container in which a cake is baked","muffin tin":"a tray containing separate cups for small cakes","pastry brush":"a small brush used to coat pastry with egg or butter","piping bag":"a flexible bag used to decorate food with cream or icing","cookie cutter":"a shaped tool that cuts repeated forms from dough","kitchen scales":"equipment used to weigh ingredients accurately","measuring spoons":"small standardised spoons used for precise quantities","oven mitt":"a heat-resistant glove used to handle hot cookware",
 "garlic press":"a handheld device that crushes garlic through small holes","can opener":"a tool designed to remove the sealed lid of a can","bottle opener":"a small tool used to remove a metal bottle cap","corkscrew":"a spiral tool used to extract a cork from a bottle","kitchen scissors":"strong scissors intended for cutting food and packaging","kitchen tongs":"a hinged tool used to grip food without touching it","potato masher":"a tool with a broad head used to crush cooked vegetables","mortar and pestle":"a two-part tool used to grind spices into a paste or powder","citrus juicer":"a device that extracts liquid from lemons and oranges",
 "slotted spoon":"a serving spoon whose holes allow liquid to drain","skimmer":"a flat perforated utensil used to remove foam from liquid","carving fork":"a long fork that holds cooked meat steady while it is sliced","serving tray":"a flat portable surface used to carry dishes and drinks","salad bowl":"a wide container in which ingredients are tossed together","pepper mill":"a grinder that crushes peppercorns immediately before use","food container":"a reusable sealed box that protects stored food","ice cube tray":"a divided mould in which small portions of water are frozen","thermos flask":"an insulated container that maintains a drink's temperature",
 "kitchen timer":"a device that counts down a precise cooking interval","cooking thermometer":"an instrument used to check the internal temperature of food","blender":"an electric appliance that turns ingredients into a smooth liquid","hand mixer":"a portable electric appliance with rotating beaters","food processor":"a powered appliance used to chop, slice or blend ingredients","electric kettle":"an appliance that heats water to boiling point","toaster":"an appliance that browns slices of bread","microwave oven":"an appliance that reheats food using electromagnetic energy","kitchen apron":"protective clothing worn over garments while cooking"
};
kitchenVisualSets.forEach(set=>set.items.forEach(item=>{item.clue??=advancedKitchenClues[item.en]}));
export const jobVisualSets:VisualSet[]=[{id:"jobs",levels:["A1","A2"],title:"Lavori e professioni",image:"images/visual-jobs-grid.png",items:[
 {en:"chef",it:"cuoco/a",verb:"cook · cucinare"},{en:"waiter",it:"cameriere",verb:"serve · servire"},{en:"nurse",it:"infermiere/a",verb:"care for · assistere"},{en:"doctor",it:"medico",verb:"treat · curare"},{en:"teacher",it:"insegnante",verb:"teach · insegnare"},{en:"mechanic",it:"meccanico",verb:"repair · riparare"},{en:"electrician",it:"elettricista",verb:"install · installare"},{en:"carpenter",it:"falegname",verb:"build · costruire"},{en:"firefighter",it:"vigile del fuoco",verb:"rescue · soccorrere"}
 ]},{id:"jobs-advanced",levels:["B1","B2","C1"],audioMode:"browser",title:"Ruoli e responsabilità professionali",image:"images/visual-jobs-grid.png",items:[
 {en:"head chef",it:"capocuoco",verb:"oversee the kitchen · dirigere la cucina",clue:"oversees food preparation and kitchen standards"},{en:"restaurant server",it:"addetto/a di sala",verb:"attend to guests · assistere i clienti",clue:"takes orders and attends to diners"},{en:"registered nurse",it:"infermiere/a abilitato/a",verb:"monitor patients · monitorare i pazienti",clue:"monitors patients and administers care"},{en:"consultant physician",it:"medico specialista",verb:"diagnose complex cases · diagnosticare casi complessi",clue:"diagnoses and advises on complex medical cases"},{en:"lecturer",it:"docente",verb:"deliver a lecture · tenere una lezione",clue:"teaches and presents material to a class"},{en:"automotive technician",it:"tecnico automobilistico",verb:"diagnose a fault · diagnosticare un guasto",clue:"diagnoses and repairs faults in vehicles"},{en:"electrical contractor",it:"installatore elettrico",verb:"wire a building · cablare un edificio",clue:"installs and maintains electrical systems"},{en:"cabinetmaker",it:"ebanista",verb:"craft fitted furniture · realizzare mobili",clue:"crafts precise wooden furniture and fittings"},{en:"fire and rescue officer",it:"operatore antincendio",verb:"respond to emergencies · intervenire nelle emergenze",clue:"responds to fires and rescues people"}
]}];

export const actionVisualSets:VisualSet[]=[{id:"actions",levels:["A1","A2"],title:"Azioni quotidiane",image:"images/visual-actions-grid.png",items:[
 {en:"sit down",it:"sedersi",verb:"sit – sat – sat"},{en:"stand up",it:"alzarsi",verb:"stand – stood – stood"},{en:"open a door",it:"aprire una porta",verb:"open · aprire"},{en:"close a window",it:"chiudere una finestra",verb:"close · chiudere"},{en:"pick up a box",it:"sollevare una scatola",verb:"pick up · raccogliere"},{en:"put down a bag",it:"posare una borsa",verb:"put down · posare"},{en:"turn on a light",it:"accendere una luce",verb:"turn on · accendere"},{en:"turn off a tap",it:"chiudere un rubinetto",verb:"turn off · spegnere/chiudere"},{en:"wash your hands",it:"lavarsi le mani",verb:"wash · lavare"}
 ]},{id:"actions-advanced",levels:["B1","B2","C1"],audioMode:"browser",title:"Azioni precise nel contesto",image:"images/visual-actions-grid.png",items:[
 {en:"take a seat",it:"accomodarsi",verb:"take a seat · accomodarsi",clue:"move into a seated position politely"},{en:"rise to your feet",it:"alzarsi in piedi",verb:"rise to your feet · alzarsi",clue:"stand after having been seated"},{en:"push the door open",it:"spingere la porta aprendola",verb:"push open · aprire spingendo",clue:"use force to create an entrance"},{en:"pull the window shut",it:"tirare la finestra chiudendola",verb:"pull shut · chiudere tirando",clue:"close an opening by pulling it"},{en:"lift the container",it:"sollevare il contenitore",verb:"lift · sollevare",clue:"raise a container from the floor"},{en:"set the luggage down",it:"posare il bagaglio",verb:"set down · posare",clue:"place luggage carefully on a surface"},{en:"switch the light on",it:"accendere la luce",verb:"switch on · accendere",clue:"activate the light using its control"},{en:"shut off the tap",it:"chiudere il rubinetto",verb:"shut off · interrompere il flusso",clue:"stop the flow of water completely"},{en:"rinse your hands thoroughly",it:"sciacquare bene le mani",verb:"rinse thoroughly · sciacquare a fondo",clue:"clean your hands carefully with water"}
]}];
export const phrasalVisualSets:VisualSet[]=[{id:"phrasal-a1",levels:["A1"],audioMode:"browser",title:"Phrasal verbs: viaggio e routine",image:"images/visual-phrasal-verbs-grid.png",items:[
 {en:"take off",it:"decollare",verb:"the plane takes off"},{en:"land",it:"atterrare",verb:"the plane lands"},{en:"get on",it:"salire su",verb:"get on the bus"},{en:"get off",it:"scendere da",verb:"get off the bus"},{en:"wake up",it:"svegliarsi",verb:"wake up early"},{en:"get dressed",it:"vestirsi",verb:"get dressed quickly"},{en:"look for",it:"cercare",verb:"look for the keys"},{en:"turn around",it:"girarsi",verb:"turn around slowly"},{en:"hurry up",it:"sbrigarsi",verb:"hurry up, please"}
 ]},{id:"phrasal-a2",levels:["A2"],audioMode:"browser",title:"Viaggio e routine: alternative",image:"images/visual-phrasal-verbs-grid.png",items:[
 {en:"lift off",it:"sollevarsi in volo",verb:"the aircraft lifts off",clue:"leave the ground and begin flying"},{en:"touch down",it:"toccare terra",verb:"the aircraft touches down",clue:"reach the runway at the end of a flight"},{en:"climb aboard",it:"salire a bordo",verb:"climb aboard the bus",clue:"enter a vehicle to begin a journey"},{en:"step off",it:"scendere",verb:"step off the bus",clue:"leave a vehicle at your stop"},{en:"get out of bed",it:"alzarsi dal letto",verb:"get out of bed early",clue:"leave your bed after waking"},{en:"put on your clothes",it:"indossare i vestiti",verb:"put on your clothes",clue:"dress yourself before leaving"},{en:"search for",it:"cercare",verb:"search for the keys",clue:"try to find something missing"},{en:"head back",it:"tornare indietro",verb:"head back home",clue:"start moving towards the place you left"},{en:"rush",it:"affrettarsi",verb:"rush to the station",clue:"move quickly because time is short"}
 ]},{id:"phrasal-b1",levels:["B1"],audioMode:"browser",title:"Phrasal verbs nel contesto",image:"images/visual-phrasal-verbs-grid.png",items:[
 {en:"set off",it:"partire",verb:"set off before dawn",clue:"begin a journey"},{en:"come in to land",it:"prepararsi all'atterraggio",verb:"come in to land",clue:"approach the runway before touching down"},{en:"hop on",it:"salire rapidamente",verb:"hop on the bus",clue:"get onto public transport quickly"},{en:"hop off",it:"scendere rapidamente",verb:"hop off at the next stop",clue:"leave public transport quickly"},{en:"sleep in",it:"dormire più del solito",verb:"sleep in at the weekend",clue:"remain in bed later than usual"},{en:"slip into",it:"indossare rapidamente",verb:"slip into a jacket",clue:"put on an item of clothing quickly"},{en:"hunt for",it:"cercare con insistenza",verb:"hunt for the missing keys",clue:"search persistently for something"},{en:"double back",it:"tornare sui propri passi",verb:"double back to the station",clue:"turn and return along the same route"},{en:"get a move on",it:"darsi una mossa",verb:"get a move on",clue:"start moving more quickly"}
 ]},{id:"phrasal-b2",levels:["B2"],audioMode:"browser",title:"Phrasal verbs avanzati",image:"images/visual-phrasal-verbs-grid.png",items:[
 {en:"get airborne",it:"prendere il volo",verb:"get airborne despite the delay",clue:"successfully leave the ground"},{en:"make a smooth landing",it:"effettuare un atterraggio morbido",verb:"make a smooth landing",clue:"complete a flight without a rough touchdown"},{en:"board",it:"salire a bordo",verb:"board the aircraft",clue:"enter a vehicle before departure"},{en:"disembark",it:"sbarcare",verb:"disembark from the aircraft",clue:"leave a vehicle after arrival"},{en:"come round",it:"riprendere conoscenza",verb:"come round gradually",clue:"regain consciousness after being unconscious"},{en:"wrap up",it:"coprirsi bene",verb:"wrap up against the cold",clue:"put on warm clothes for protection"},{en:"track down",it:"rintracciare",verb:"track down the missing item",clue:"find something after a determined search"},{en:"retrace your steps",it:"ripercorrere i propri passi",verb:"retrace your steps",clue:"follow the same route backwards"},{en:"press on",it:"proseguire con decisione",verb:"press on despite the delay",clue:"continue moving despite difficulty"}
 ]},{id:"phrasal-c1",levels:["C1"],audioMode:"browser",title:"Registro e sfumature di movimento",image:"images/visual-phrasal-verbs-grid.png",items:[
 {en:"become airborne",it:"levarsi in volo",verb:"become airborne",clue:"transition from ground movement to flight"},{en:"touch down safely",it:"atterrare in sicurezza",verb:"touch down safely",clue:"complete the airborne phase on the runway"},{en:"embark",it:"imbarcarsi",verb:"embark on the service",clue:"enter transport in a formal register"},{en:"alight",it:"scendere da un mezzo",verb:"alight from the vehicle",clue:"leave public transport in a formal register"},{en:"regain consciousness",it:"riprendere conoscenza",verb:"regain consciousness",clue:"return to an aware state"},{en:"don protective clothing",it:"indossare abiti protettivi",verb:"don protective clothing",clue:"put on clothing in formal usage"},{en:"seek out",it:"ricercare attivamente",verb:"seek out the missing evidence",clue:"make a deliberate effort to locate something"},{en:"reverse course",it:"invertire la direzione",verb:"reverse course immediately",clue:"change direction and return"},{en:"make haste",it:"affrettarsi",verb:"make haste",clue:"move quickly in a formal or literary register"}
]}];

export function visualSetsForLevel(sets:VisualSet[],level:Cefr){return sets.filter(set=>!set.levels||set.levels.includes(level))}
